// Written by Jürgen Moßgraber - mossgrabers.de
// (c) 2017-2023
// Licensed under LGPLv3 - http://www.gnu.org/licenses/lgpl-3.0.txt

package de.mossgrabers.controller.generic.controller;

import java.util.HashMap;
import java.util.Map;


/**
 * All available commands.
 *
 * @author Jürgen Moßgraber
 */
@SuppressWarnings("javadoc")
public enum FlexiCommand
{
    OFF(null, "Off", false),

    GLOBAL_UNDO(CommandCategory.GLOBAL, "Global: Undo", true),
    GLOBAL_REDO(CommandCategory.GLOBAL, "Global: Redo", true),
    GLOBAL_PREVIOUS_PROJECT(CommandCategory.GLOBAL, "Global: Previous Project", true),
    GLOBAL_NEXT_PROJECT(CommandCategory.GLOBAL, "Global: Next Project", true),
    GLOBAL_TOGGLE_AUDIO_ENGINE(CommandCategory.GLOBAL, "Global: Toggle Audio Engine", true),
    GLOBAL_SHIFT_BUTTON(CommandCategory.GLOBAL, "Global: Shift Button", true),

    TRANSPORT_PLAY(CommandCategory.TRANSPORT, "Transport: Play", true),
    TRANSPORT_STOP(CommandCategory.TRANSPORT, "Transport: Stop", true),
    TRANSPORT_RESTART(CommandCategory.TRANSPORT, "Transport: Restart", true),
    TRANSPORT_REWIND(CommandCategory.TRANSPORT, "Transport: Rewind", true),
    TRANSPORT_FAST_FORWARD(CommandCategory.TRANSPORT, "Transport: Fast Forward", true),
    TRANSPORT_TOGGLE_REPEAT(CommandCategory.TRANSPORT, "Transport: Toggle Repeat", true),
    TRANSPORT_TOGGLE_METRONOME(CommandCategory.TRANSPORT, "Transport: Toggle Metronome", true),
    TRANSPORT_SET_METRONOME_VOLUME(CommandCategory.TRANSPORT, "Transport: Set Metronome Volume", false),
    TRANSPORT_TOGGLE_METRONOME_IN_PREROLL(CommandCategory.TRANSPORT, "Transport: Toggle Metronome in Pre-roll", true),
    TRANSPORT_TOGGLE_PUNCH_IN(CommandCategory.TRANSPORT, "Transport: Toggle Punch In", true),
    TRANSPORT_TOGGLE_PUNCH_OUT(CommandCategory.TRANSPORT, "Transport: Toggle Punch Out", true),
    TRANSPORT_TOGGLE_RECORD(CommandCategory.TRANSPORT, "Transport: Toggle Record", true),
    TRANSPORT_TOGGLE_ARRANGER_OVERDUB(CommandCategory.TRANSPORT, "Transport: Toggle Arranger Overdub", true),
    TRANSPORT_TOGGLE_CLIP_OVERDUB(CommandCategory.TRANSPORT, "Transport: Toggle Clip Overdub", true),
    TRANSPORT_TOGGLE_ARRANGER_AUTOMATION_WRITE(CommandCategory.TRANSPORT, "Transport: Toggle Arranger Automation Write", true),
    TRANSPORT_TOGGLE_CLIP_AUTOMATION_WRITE(CommandCategory.TRANSPORT, "Transport: Toggle Clip Automation Write", true),
    TRANSPORT_SET_WRITE_MODE_LATCH(CommandCategory.TRANSPORT, "Transport: Set Write Mode: Latch", true),
    TRANSPORT_SET_WRITE_MODE_TOUCH(CommandCategory.TRANSPORT, "Transport: Set Write Mode: Touch", true),
    TRANSPORT_SET_WRITE_MODE_WRITE(CommandCategory.TRANSPORT, "Transport: Set Write Mode: Write", true),
    TRANSPORT_SET_TEMPO(CommandCategory.TRANSPORT, "Transport: Set Tempo", false),
    TRANSPORT_TAP_TEMPO(CommandCategory.TRANSPORT, "Transport: Tap Tempo", true),
    TRANSPORT_MOVE_PLAY_CURSOR(CommandCategory.TRANSPORT, "Transport: Move Play Cursor", false),

    LAYOUT_ARRANGER_ZOOM_IN(CommandCategory.LAYOUT, "Layout: Zoom in arranger timeline", true),
    LAYOUT_ARRANGER_ZOOM_OUT(CommandCategory.LAYOUT, "Layout: Zoom out arranger timeline", true),
    LAYOUT_SET_ARRANGE_LAYOUT(CommandCategory.LAYOUT, "Layout: Set Arrange Layout", true),
    LAYOUT_SET_MIX_LAYOUT(CommandCategory.LAYOUT, "Layout: Set Mix Layout", true),
    LAYOUT_SET_EDIT_LAYOUT(CommandCategory.LAYOUT, "Layout: Set Edit Layout", true),
    LAYOUT_TOGGLE_NOTE_EDITOR(CommandCategory.LAYOUT, "Layout: Toggle Note Editor", true),
    LAYOUT_TOGGLE_AUTOMATION_EDITOR(CommandCategory.LAYOUT, "Layout: Toggle Automation Editor", true),
    LAYOUT_TOGGLE_DEVICES_PANEL(CommandCategory.LAYOUT, "Layout: Toggle Devices Panel", true),
    LAYOUT_TOGGLE_MIXER_PANEL(CommandCategory.LAYOUT, "Layout: Toggle Mixer Panel", true),
    LAYOUT_TOGGLE_FULLSCREEN(CommandCategory.LAYOUT, "Layout: Toggle Fullscreen", true),
    LAYOUT_TOGGLE_ARRANGER_CUE_MARKERS(CommandCategory.LAYOUT, "Layout: Toggle Arranger Cue Markers", true),
    LAYOUT_TOGGLE_ARRANGER_PLAYBACK_FOLLOW(CommandCategory.LAYOUT, "Layout: Toggle Arranger Playback Follow", true),
    LAYOUT_TOGGLE_ARRANGER_TRACK_ROW_HEIGHT(CommandCategory.LAYOUT, "Layout: Toggle Arranger Track Row Height", true),
    LAYOUT_TOGGLE_ARRANGER_CLIP_LAUNCHER_SECTION(CommandCategory.LAYOUT, "Layout: Toggle Arranger Clip Launcher Section", true),
    LAYOUT_TOGGLE_ARRANGER_TIME_LINE(CommandCategory.LAYOUT, "Layout: Toggle Arranger Time Line", true),
    LAYOUT_TOGGLE_ARRANGER_IO_SECTION(CommandCategory.LAYOUT, "Layout: Toggle Arranger IO Section", true),
    LAYOUT_TOGGLE_ARRANGER_EFFECT_TRACKS(CommandCategory.LAYOUT, "Layout: Toggle Arranger Effect Tracks", true),
    LAYOUT_TOGGLE_MIXER_CLIP_LAUNCHER_SECTION(CommandCategory.LAYOUT, "Layout: Toggle Mixer Clip Launcher Section", true),
    LAYOUT_TOGGLE_MIXER_CROSS_FADE_SECTION(CommandCategory.LAYOUT, "Layout: Toggle Mixer Cross Fade Section", true),
    LAYOUT_TOGGLE_MIXER_DEVICE_SECTION(CommandCategory.LAYOUT, "Layout: Toggle Mixer Device Section", true),
    LAYOUT_TOGGLE_MIXER_SENDSSECTION(CommandCategory.LAYOUT, "Layout: Toggle Mixer sendsSection", true),
    LAYOUT_TOGGLE_MIXER_IO_SECTION(CommandCategory.LAYOUT, "Layout: Toggle Mixer IO Section", true),
    LAYOUT_TOGGLE_MIXER_METER_SECTION(CommandCategory.LAYOUT, "Layout: Toggle Mixer Meter Section", true),

    TRACK_TOGGLE_TRACK_BANK(CommandCategory.TRACK, "Track: Toggle Trackbank", true),
    TRACK_ADD_AUDIO_TRACK(CommandCategory.TRACK, "Track: Add Audio Track", true),
    TRACK_ADD_EFFECT_TRACK(CommandCategory.TRACK, "Track: Add Effect Track", true),
    TRACK_ADD_INSTRUMENT_TRACK(CommandCategory.TRACK, "Track: Add Instrument Track", true),
    TRACK_SELECT_PREVIOUS_BANK_PAGE(CommandCategory.TRACK, "Track: Select Previous Bank Page", true),
    TRACK_SELECT_NEXT_BANK_PAGE(CommandCategory.TRACK, "Track: Select Next Bank Page", true),
    TRACK_SELECT_PREVIOUS_TRACK(CommandCategory.TRACK, "Track: Select Previous Track", true),
    TRACK_SELECT_NEXT_TRACK(CommandCategory.TRACK, "Track: Select Next Track", true),
    TRACK_SCROLL_TRACKS(CommandCategory.TRACK, "Track: Scroll Tracks", false),
    TRACK_1_SELECT(CommandCategory.TRACK, "Track 1: Select", true),
    TRACK_2_SELECT(CommandCategory.TRACK, "Track 2: Select", true),
    TRACK_3_SELECT(CommandCategory.TRACK, "Track 3: Select", true),
    TRACK_4_SELECT(CommandCategory.TRACK, "Track 4: Select", true),
    TRACK_5_SELECT(CommandCategory.TRACK, "Track 5: Select", true),
    TRACK_6_SELECT(CommandCategory.TRACK, "Track 6: Select", true),
    TRACK_7_SELECT(CommandCategory.TRACK, "Track 7: Select", true),
    TRACK_8_SELECT(CommandCategory.TRACK, "Track 8: Select", true),
    TRACK_1_TOGGLE_ACTIVE(CommandCategory.TRACK, "Track 1: Toggle Active", true),
    TRACK_2_TOGGLE_ACTIVE(CommandCategory.TRACK, "Track 2: Toggle Active", true),
    TRACK_3_TOGGLE_ACTIVE(CommandCategory.TRACK, "Track 3: Toggle Active", true),
    TRACK_4_TOGGLE_ACTIVE(CommandCategory.TRACK, "Track 4: Toggle Active", true),
    TRACK_5_TOGGLE_ACTIVE(CommandCategory.TRACK, "Track 5: Toggle Active", true),
    TRACK_6_TOGGLE_ACTIVE(CommandCategory.TRACK, "Track 6: Toggle Active", true),
    TRACK_7_TOGGLE_ACTIVE(CommandCategory.TRACK, "Track 7: Toggle Active", true),
    TRACK_8_TOGGLE_ACTIVE(CommandCategory.TRACK, "Track 8: Toggle Active", true),
    TRACK_SELECTED_TOGGLE_ACTIVE(CommandCategory.TRACK, "Track Selected: Toggle Active", true),
    TRACK_1_SET_ACTIVE(CommandCategory.TRACK, "Track 1: Set Active", true),
    TRACK_2_SET_ACTIVE(CommandCategory.TRACK, "Track 2: Set Active", true),
    TRACK_3_SET_ACTIVE(CommandCategory.TRACK, "Track 3: Set Active", true),
    TRACK_4_SET_ACTIVE(CommandCategory.TRACK, "Track 4: Set Active", true),
    TRACK_5_SET_ACTIVE(CommandCategory.TRACK, "Track 5: Set Active", true),
    TRACK_6_SET_ACTIVE(CommandCategory.TRACK, "Track 6: Set Active", true),
    TRACK_7_SET_ACTIVE(CommandCategory.TRACK, "Track 7: Set Active", true),
    TRACK_8_SET_ACTIVE(CommandCategory.TRACK, "Track 8: Set Active", true),
    TRACK_SELECTED_SET_ACTIVE(CommandCategory.TRACK, "Track Selected: Set Active", true),
    TRACK_1_SET_VOLUME(CommandCategory.TRACK, "Track 1: Set Volume", false),
    TRACK_2_SET_VOLUME(CommandCategory.TRACK, "Track 2: Set Volume", false),
    TRACK_3_SET_VOLUME(CommandCategory.TRACK, "Track 3: Set Volume", false),
    TRACK_4_SET_VOLUME(CommandCategory.TRACK, "Track 4: Set Volume", false),
    TRACK_5_SET_VOLUME(CommandCategory.TRACK, "Track 5: Set Volume", false),
    TRACK_6_SET_VOLUME(CommandCategory.TRACK, "Track 6: Set Volume", false),
    TRACK_7_SET_VOLUME(CommandCategory.TRACK, "Track 7: Set Volume", false),
    TRACK_8_SET_VOLUME(CommandCategory.TRACK, "Track 8: Set Volume", false),
    TRACK_SELECTED_SET_VOLUME_TRACK(CommandCategory.TRACK, "Track Selected: Set Volume Track", false),
    TRACK_1_SET_PANORAMA(CommandCategory.TRACK, "Track 1: Set Panorama", false),
    TRACK_2_SET_PANORAMA(CommandCategory.TRACK, "Track 2: Set Panorama", false),
    TRACK_3_SET_PANORAMA(CommandCategory.TRACK, "Track 3: Set Panorama", false),
    TRACK_4_SET_PANORAMA(CommandCategory.TRACK, "Track 4: Set Panorama", false),
    TRACK_5_SET_PANORAMA(CommandCategory.TRACK, "Track 5: Set Panorama", false),
    TRACK_6_SET_PANORAMA(CommandCategory.TRACK, "Track 6: Set Panorama", false),
    TRACK_7_SET_PANORAMA(CommandCategory.TRACK, "Track 7: Set Panorama", false),
    TRACK_8_SET_PANORAMA(CommandCategory.TRACK, "Track 8: Set Panorama", false),
    TRACK_SELECTED_SET_PANORAMA(CommandCategory.TRACK, "Track Selected: Set Panorama", false),
    TRACK_1_TOGGLE_MUTE(CommandCategory.TRACK, "Track 1: Toggle Mute", true),
    TRACK_2_TOGGLE_MUTE(CommandCategory.TRACK, "Track 2: Toggle Mute", true),
    TRACK_3_TOGGLE_MUTE(CommandCategory.TRACK, "Track 3: Toggle Mute", true),
    TRACK_4_TOGGLE_MUTE(CommandCategory.TRACK, "Track 4: Toggle Mute", true),
    TRACK_5_TOGGLE_MUTE(CommandCategory.TRACK, "Track 5: Toggle Mute", true),
    TRACK_6_TOGGLE_MUTE(CommandCategory.TRACK, "Track 6: Toggle Mute", true),
    TRACK_7_TOGGLE_MUTE(CommandCategory.TRACK, "Track 7: Toggle Mute", true),
    TRACK_8_TOGGLE_MUTE(CommandCategory.TRACK, "Track 8: Toggle Mute", true),
    TRACK_SELECTED_TOGGLE_MUTE(CommandCategory.TRACK, "Track Selected: Toggle Mute", true),
    TRACK_1_SET_MUTE(CommandCategory.TRACK, "Track 1: Set Mute", true),
    TRACK_2_SET_MUTE(CommandCategory.TRACK, "Track 2: Set Mute", true),
    TRACK_3_SET_MUTE(CommandCategory.TRACK, "Track 3: Set Mute", true),
    TRACK_4_SET_MUTE(CommandCategory.TRACK, "Track 4: Set Mute", true),
    TRACK_5_SET_MUTE(CommandCategory.TRACK, "Track 5: Set Mute", true),
    TRACK_6_SET_MUTE(CommandCategory.TRACK, "Track 6: Set Mute", true),
    TRACK_7_SET_MUTE(CommandCategory.TRACK, "Track 7: Set Mute", true),
    TRACK_8_SET_MUTE(CommandCategory.TRACK, "Track 8: Set Mute", true),
    TRACK_SELECTED_SET_MUTE(CommandCategory.TRACK, "Track Selected: Set Mute", true),
    TRACK_1_TOGGLE_SOLO(CommandCategory.TRACK, "Track 1: Toggle Solo", true),
    TRACK_2_TOGGLE_SOLO(CommandCategory.TRACK, "Track 2: Toggle Solo", true),
    TRACK_3_TOGGLE_SOLO(CommandCategory.TRACK, "Track 3: Toggle Solo", true),
    TRACK_4_TOGGLE_SOLO(CommandCategory.TRACK, "Track 4: Toggle Solo", true),
    TRACK_5_TOGGLE_SOLO(CommandCategory.TRACK, "Track 5: Toggle Solo", true),
    TRACK_6_TOGGLE_SOLO(CommandCategory.TRACK, "Track 6: Toggle Solo", true),
    TRACK_7_TOGGLE_SOLO(CommandCategory.TRACK, "Track 7: Toggle Solo", true),
    TRACK_8_TOGGLE_SOLO(CommandCategory.TRACK, "Track 8: Toggle Solo", true),
    TRACK_SELECTED_TOGGLE_SOLO(CommandCategory.TRACK, "Track Selected: Toggle Solo", true),
    TRACK_1_SET_SOLO(CommandCategory.TRACK, "Track 1: Set Solo", true),
    TRACK_2_SET_SOLO(CommandCategory.TRACK, "Track 2: Set Solo", true),
    TRACK_3_SET_SOLO(CommandCategory.TRACK, "Track 3: Set Solo", true),
    TRACK_4_SET_SOLO(CommandCategory.TRACK, "Track 4: Set Solo", true),
    TRACK_5_SET_SOLO(CommandCategory.TRACK, "Track 5: Set Solo", true),
    TRACK_6_SET_SOLO(CommandCategory.TRACK, "Track 6: Set Solo", true),
    TRACK_7_SET_SOLO(CommandCategory.TRACK, "Track 7: Set Solo", true),
    TRACK_8_SET_SOLO(CommandCategory.TRACK, "Track 8: Set Solo", true),
    TRACK_SELECTED_SET_SOLO(CommandCategory.TRACK, "Track Selected: Set Solo", true),
    TRACK_1_TOGGLE_ARM(CommandCategory.TRACK, "Track 1: Toggle Arm", true),
    TRACK_2_TOGGLE_ARM(CommandCategory.TRACK, "Track 2: Toggle Arm", true),
    TRACK_3_TOGGLE_ARM(CommandCategory.TRACK, "Track 3: Toggle Arm", true),
    TRACK_4_TOGGLE_ARM(CommandCategory.TRACK, "Track 4: Toggle Arm", true),
    TRACK_5_TOGGLE_ARM(CommandCategory.TRACK, "Track 5: Toggle Arm", true),
    TRACK_6_TOGGLE_ARM(CommandCategory.TRACK, "Track 6: Toggle Arm", true),
    TRACK_7_TOGGLE_ARM(CommandCategory.TRACK, "Track 7: Toggle Arm", true),
    TRACK_8_TOGGLE_ARM(CommandCategory.TRACK, "Track 8: Toggle Arm", true),
    TRACK_SELECTED_TOGGLE_ARM(CommandCategory.TRACK, "Track Selected: Toggle Arm", true),
    TRACK_1_SET_ARM(CommandCategory.TRACK, "Track 1: Set Arm", true),
    TRACK_2_SET_ARM(CommandCategory.TRACK, "Track 2: Set Arm", true),
    TRACK_3_SET_ARM(CommandCategory.TRACK, "Track 3: Set Arm", true),
    TRACK_4_SET_ARM(CommandCategory.TRACK, "Track 4: Set Arm", true),
    TRACK_5_SET_ARM(CommandCategory.TRACK, "Track 5: Set Arm", true),
    TRACK_6_SET_ARM(CommandCategory.TRACK, "Track 6: Set Arm", true),
    TRACK_7_SET_ARM(CommandCategory.TRACK, "Track 7: Set Arm", true),
    TRACK_8_SET_ARM(CommandCategory.TRACK, "Track 8: Set Arm", true),
    TRACK_SELECTED_SET_ARM(CommandCategory.TRACK, "Track Selected: Set Arm", true),
    TRACK_1_TOGGLE_MONITOR(CommandCategory.TRACK, "Track 1: Toggle Monitor", true),
    TRACK_2_TOGGLE_MONITOR(CommandCategory.TRACK, "Track 2: Toggle Monitor", true),
    TRACK_3_TOGGLE_MONITOR(CommandCategory.TRACK, "Track 3: Toggle Monitor", true),
    TRACK_4_TOGGLE_MONITOR(CommandCategory.TRACK, "Track 4: Toggle Monitor", true),
    TRACK_5_TOGGLE_MONITOR(CommandCategory.TRACK, "Track 5: Toggle Monitor", true),
    TRACK_6_TOGGLE_MONITOR(CommandCategory.TRACK, "Track 6: Toggle Monitor", true),
    TRACK_7_TOGGLE_MONITOR(CommandCategory.TRACK, "Track 7: Toggle Monitor", true),
    TRACK_8_TOGGLE_MONITOR(CommandCategory.TRACK, "Track 8: Toggle Monitor", true),
    TRACK_SELECTED_TOGGLE_MONITOR(CommandCategory.TRACK, "Track Selected: Toggle Monitor", true),
    TRACK_1_SET_MONITOR(CommandCategory.TRACK, "Track 1: Set Monitor", true),
    TRACK_2_SET_MONITOR(CommandCategory.TRACK, "Track 2: Set Monitor", true),
    TRACK_3_SET_MONITOR(CommandCategory.TRACK, "Track 3: Set Monitor", true),
    TRACK_4_SET_MONITOR(CommandCategory.TRACK, "Track 4: Set Monitor", true),
    TRACK_5_SET_MONITOR(CommandCategory.TRACK, "Track 5: Set Monitor", true),
    TRACK_6_SET_MONITOR(CommandCategory.TRACK, "Track 6: Set Monitor", true),
    TRACK_7_SET_MONITOR(CommandCategory.TRACK, "Track 7: Set Monitor", true),
    TRACK_8_SET_MONITOR(CommandCategory.TRACK, "Track 8: Set Monitor", true),
    TRACK_SELECTED_SET_MONITOR(CommandCategory.TRACK, "Track Selected: Set Monitor", true),
    TRACK_1_TOGGLE_AUTO_MONITOR(CommandCategory.TRACK, "Track 1: Toggle Auto Monitor", true),
    TRACK_2_TOGGLE_AUTO_MONITOR(CommandCategory.TRACK, "Track 2: Toggle Auto Monitor", true),
    TRACK_3_TOGGLE_AUTO_MONITOR(CommandCategory.TRACK, "Track 3: Toggle Auto Monitor", true),
    TRACK_4_TOGGLE_AUTO_MONITOR(CommandCategory.TRACK, "Track 4: Toggle Auto Monitor", true),
    TRACK_5_TOGGLE_AUTO_MONITOR(CommandCategory.TRACK, "Track 5: Toggle Auto Monitor", true),
    TRACK_6_TOGGLE_AUTO_MONITOR(CommandCategory.TRACK, "Track 6: Toggle Auto Monitor", true),
    TRACK_7_TOGGLE_AUTO_MONITOR(CommandCategory.TRACK, "Track 7: Toggle Auto Monitor", true),
    TRACK_8_TOGGLE_AUTO_MONITOR(CommandCategory.TRACK, "Track 8: Toggle Auto Monitor", true),
    TRACK_SELECTED_TOGGLE_AUTO_MONITOR(CommandCategory.TRACK, "Track Selected: Toggle Auto Monitor", true),
    TRACK_1_SET_AUTO_MONITOR(CommandCategory.TRACK, "Track 1: Set Auto Monitor", true),
    TRACK_2_SET_AUTO_MONITOR(CommandCategory.TRACK, "Track 2: Set Auto Monitor", true),
    TRACK_3_SET_AUTO_MONITOR(CommandCategory.TRACK, "Track 3: Set Auto Monitor", true),
    TRACK_4_SET_AUTO_MONITOR(CommandCategory.TRACK, "Track 4: Set Auto Monitor", true),
    TRACK_5_SET_AUTO_MONITOR(CommandCategory.TRACK, "Track 5: Set Auto Monitor", true),
    TRACK_6_SET_AUTO_MONITOR(CommandCategory.TRACK, "Track 6: Set Auto Monitor", true),
    TRACK_7_SET_AUTO_MONITOR(CommandCategory.TRACK, "Track 7: Set Auto Monitor", true),
    TRACK_8_SET_AUTO_MONITOR(CommandCategory.TRACK, "Track 8: Set Auto Monitor", true),
    TRACK_SELECTED_SET_AUTO_MONITOR(CommandCategory.TRACK, "Track Selected: Set Auto Monitor", true),
    TRACK_SELECTED_TOGGLE_PIN(CommandCategory.TRACK, "Track Selected: Toggle Pin", true),
    TRACK_SELECTED_SET_PIN(CommandCategory.TRACK, "Track Selected: Set Pin", true),
    TRACK_1_SET_SEND_1(CommandCategory.TRACK, "Track 1: Set Send 1", false),
    TRACK_2_SET_SEND_1(CommandCategory.TRACK, "Track 2: Set Send 1", false),
    TRACK_3_SET_SEND_1(CommandCategory.TRACK, "Track 3: Set Send 1", false),
    TRACK_4_SET_SEND_1(CommandCategory.TRACK, "Track 4: Set Send 1", false),
    TRACK_5_SET_SEND_1(CommandCategory.TRACK, "Track 5: Set Send 1", false),
    TRACK_6_SET_SEND_1(CommandCategory.TRACK, "Track 6: Set Send 1", false),
    TRACK_7_SET_SEND_1(CommandCategory.TRACK, "Track 7: Set Send 1", false),
    TRACK_8_SET_SEND_1(CommandCategory.TRACK, "Track 8: Set Send 1", false),
    TRACK_1_SET_SEND_2(CommandCategory.TRACK, "Track 1: Set Send 2", false),
    TRACK_2_SET_SEND_2(CommandCategory.TRACK, "Track 2: Set Send 2", false),
    TRACK_3_SET_SEND_2(CommandCategory.TRACK, "Track 3: Set Send 2", false),
    TRACK_4_SET_SEND_2(CommandCategory.TRACK, "Track 4: Set Send 2", false),
    TRACK_5_SET_SEND_2(CommandCategory.TRACK, "Track 5: Set Send 2", false),
    TRACK_6_SET_SEND_2(CommandCategory.TRACK, "Track 6: Set Send 2", false),
    TRACK_7_SET_SEND_2(CommandCategory.TRACK, "Track 7: Set Send 2", false),
    TRACK_8_SET_SEND_2(CommandCategory.TRACK, "Track 8: Set Send 2", false),
    TRACK_1_SET_SEND_3(CommandCategory.TRACK, "Track 1: Set Send 3", false),
    TRACK_2_SET_SEND_3(CommandCategory.TRACK, "Track 2: Set Send 3", false),
    TRACK_3_SET_SEND_3(CommandCategory.TRACK, "Track 3: Set Send 3", false),
    TRACK_4_SET_SEND_3(CommandCategory.TRACK, "Track 4: Set Send 3", false),
    TRACK_5_SET_SEND_3(CommandCategory.TRACK, "Track 5: Set Send 3", false),
    TRACK_6_SET_SEND_3(CommandCategory.TRACK, "Track 6: Set Send 3", false),
    TRACK_7_SET_SEND_3(CommandCategory.TRACK, "Track 7: Set Send 3", false),
    TRACK_8_SET_SEND_3(CommandCategory.TRACK, "Track 8: Set Send 3", false),
    TRACK_1_SET_SEND_4(CommandCategory.TRACK, "Track 1: Set Send 4", false),
    TRACK_2_SET_SEND_4(CommandCategory.TRACK, "Track 2: Set Send 4", false),
    TRACK_3_SET_SEND_4(CommandCategory.TRACK, "Track 3: Set Send 4", false),
    TRACK_4_SET_SEND_4(CommandCategory.TRACK, "Track 4: Set Send 4", false),
    TRACK_5_SET_SEND_4(CommandCategory.TRACK, "Track 5: Set Send 4", false),
    TRACK_6_SET_SEND_4(CommandCategory.TRACK, "Track 6: Set Send 4", false),
    TRACK_7_SET_SEND_4(CommandCategory.TRACK, "Track 7: Set Send 4", false),
    TRACK_8_SET_SEND_4(CommandCategory.TRACK, "Track 8: Set Send 4", false),
    TRACK_1_SET_SEND_5(CommandCategory.TRACK, "Track 1: Set Send 5", false),
    TRACK_2_SET_SEND_5(CommandCategory.TRACK, "Track 2: Set Send 5", false),
    TRACK_3_SET_SEND_5(CommandCategory.TRACK, "Track 3: Set Send 5", false),
    TRACK_4_SET_SEND_5(CommandCategory.TRACK, "Track 4: Set Send 5", false),
    TRACK_5_SET_SEND_5(CommandCategory.TRACK, "Track 5: Set Send 5", false),
    TRACK_6_SET_SEND_5(CommandCategory.TRACK, "Track 6: Set Send 5", false),
    TRACK_7_SET_SEND_5(CommandCategory.TRACK, "Track 7: Set Send 5", false),
    TRACK_8_SET_SEND_5(CommandCategory.TRACK, "Track 8: Set Send 5", false),
    TRACK_1_SET_SEND_6(CommandCategory.TRACK, "Track 1: Set Send 6", false),
    TRACK_2_SET_SEND_6(CommandCategory.TRACK, "Track 2: Set Send 6", false),
    TRACK_3_SET_SEND_6(CommandCategory.TRACK, "Track 3: Set Send 6", false),
    TRACK_4_SET_SEND_6(CommandCategory.TRACK, "Track 4: Set Send 6", false),
    TRACK_5_SET_SEND_6(CommandCategory.TRACK, "Track 5: Set Send 6", false),
    TRACK_6_SET_SEND_6(CommandCategory.TRACK, "Track 6: Set Send 6", false),
    TRACK_7_SET_SEND_6(CommandCategory.TRACK, "Track 7: Set Send 6", false),
    TRACK_8_SET_SEND_6(CommandCategory.TRACK, "Track 8: Set Send 6", false),
    TRACK_1_SET_SEND_7(CommandCategory.TRACK, "Track 1: Set Send 7", false),
    TRACK_2_SET_SEND_7(CommandCategory.TRACK, "Track 2: Set Send 7", false),
    TRACK_3_SET_SEND_7(CommandCategory.TRACK, "Track 3: Set Send 7", false),
    TRACK_4_SET_SEND_7(CommandCategory.TRACK, "Track 4: Set Send 7", false),
    TRACK_5_SET_SEND_7(CommandCategory.TRACK, "Track 5: Set Send 7", false),
    TRACK_6_SET_SEND_7(CommandCategory.TRACK, "Track 6: Set Send 7", false),
    TRACK_7_SET_SEND_7(CommandCategory.TRACK, "Track 7: Set Send 7", false),
    TRACK_8_SET_SEND_7(CommandCategory.TRACK, "Track 8: Set Send 7", false),
    TRACK_1_SET_SEND_8(CommandCategory.TRACK, "Track 1: Set Send 8", false),
    TRACK_2_SET_SEND_8(CommandCategory.TRACK, "Track 2: Set Send 8", false),
    TRACK_3_SET_SEND_8(CommandCategory.TRACK, "Track 3: Set Send 8", false),
    TRACK_4_SET_SEND_8(CommandCategory.TRACK, "Track 4: Set Send 8", false),
    TRACK_5_SET_SEND_8(CommandCategory.TRACK, "Track 5: Set Send 8", false),
    TRACK_6_SET_SEND_8(CommandCategory.TRACK, "Track 6: Set Send 8", false),
    TRACK_7_SET_SEND_8(CommandCategory.TRACK, "Track 7: Set Send 8", false),
    TRACK_8_SET_SEND_8(CommandCategory.TRACK, "Track 8: Set Send 8", false),
    TRACK_SELECTED_SET_SEND_1(CommandCategory.TRACK, "Track Selected: Set Send 1", false),
    TRACK_SELECTED_SET_SEND_2(CommandCategory.TRACK, "Track Selected: Set Send 2", false),
    TRACK_SELECTED_SET_SEND_3(CommandCategory.TRACK, "Track Selected: Set Send 3", false),
    TRACK_SELECTED_SET_SEND_4(CommandCategory.TRACK, "Track Selected: Set Send 4", false),
    TRACK_SELECTED_SET_SEND_5(CommandCategory.TRACK, "Track Selected: Set Send 5", false),
    TRACK_SELECTED_SET_SEND_6(CommandCategory.TRACK, "Track Selected: Set Send 6", false),
    TRACK_SELECTED_SET_SEND_7(CommandCategory.TRACK, "Track Selected: Set Send 7", false),
    TRACK_SELECTED_SET_SEND_8(CommandCategory.TRACK, "Track Selected: Set Send 8", false),

    FX_TRACK_SELECT_PREVIOUS_BANK_PAGE(CommandCategory.FX_TRACK, "FX Track: Select Previous Bank Page", true),
    FX_TRACK_SELECT_NEXT_BANK_PAGE(CommandCategory.FX_TRACK, "FX Track: Select Next Bank Page", true),
    FX_TRACK_SELECT_PREVIOUS_TRACK(CommandCategory.FX_TRACK, "FX Track: Select Previous Track", true),
    FX_TRACK_SELECT_NEXT_TRACK(CommandCategory.FX_TRACK, "FX Track: Select Next Track", true),
    FX_TRACK_SCROLL_TRACKS(CommandCategory.FX_TRACK, "FX Track: Scroll Tracks", false),
    FX_TRACK_1_SELECT(CommandCategory.FX_TRACK, "FX Track 1: Select", true),
    FX_TRACK_2_SELECT(CommandCategory.FX_TRACK, "FX Track 2: Select", true),
    FX_TRACK_3_SELECT(CommandCategory.FX_TRACK, "FX Track 3: Select", true),
    FX_TRACK_4_SELECT(CommandCategory.FX_TRACK, "FX Track 4: Select", true),
    FX_TRACK_5_SELECT(CommandCategory.FX_TRACK, "FX Track 5: Select", true),
    FX_TRACK_6_SELECT(CommandCategory.FX_TRACK, "FX Track 6: Select", true),
    FX_TRACK_7_SELECT(CommandCategory.FX_TRACK, "FX Track 7: Select", true),
    FX_TRACK_8_SELECT(CommandCategory.FX_TRACK, "FX Track 8: Select", true),
    FX_TRACK_1_TOGGLE_ACTIVE(CommandCategory.FX_TRACK, "FX Track 1: Toggle Active", true),
    FX_TRACK_2_TOGGLE_ACTIVE(CommandCategory.FX_TRACK, "FX Track 2: Toggle Active", true),
    FX_TRACK_3_TOGGLE_ACTIVE(CommandCategory.FX_TRACK, "FX Track 3: Toggle Active", true),
    FX_TRACK_4_TOGGLE_ACTIVE(CommandCategory.FX_TRACK, "FX Track 4: Toggle Active", true),
    FX_TRACK_5_TOGGLE_ACTIVE(CommandCategory.FX_TRACK, "FX Track 5: Toggle Active", true),
    FX_TRACK_6_TOGGLE_ACTIVE(CommandCategory.FX_TRACK, "FX Track 6: Toggle Active", true),
    FX_TRACK_7_TOGGLE_ACTIVE(CommandCategory.FX_TRACK, "FX Track 7: Toggle Active", true),
    FX_TRACK_8_TOGGLE_ACTIVE(CommandCategory.FX_TRACK, "FX Track 8: Toggle Active", true),
    FX_TRACK_1_SET_ACTIVE(CommandCategory.FX_TRACK, "FX Track 1: Set Active", true),
    FX_TRACK_2_SET_ACTIVE(CommandCategory.FX_TRACK, "FX Track 2: Set Active", true),
    FX_TRACK_3_SET_ACTIVE(CommandCategory.FX_TRACK, "FX Track 3: Set Active", true),
    FX_TRACK_4_SET_ACTIVE(CommandCategory.FX_TRACK, "FX Track 4: Set Active", true),
    FX_TRACK_5_SET_ACTIVE(CommandCategory.FX_TRACK, "FX Track 5: Set Active", true),
    FX_TRACK_6_SET_ACTIVE(CommandCategory.FX_TRACK, "FX Track 6: Set Active", true),
    FX_TRACK_7_SET_ACTIVE(CommandCategory.FX_TRACK, "FX Track 7: Set Active", true),
    FX_TRACK_8_SET_ACTIVE(CommandCategory.FX_TRACK, "FX Track 8: Set Active", true),
    FX_TRACK_1_SET_VOLUME(CommandCategory.FX_TRACK, "FX Track 1: Set Volume", false),
    FX_TRACK_2_SET_VOLUME(CommandCategory.FX_TRACK, "FX Track 2: Set Volume", false),
    FX_TRACK_3_SET_VOLUME(CommandCategory.FX_TRACK, "FX Track 3: Set Volume", false),
    FX_TRACK_4_SET_VOLUME(CommandCategory.FX_TRACK, "FX Track 4: Set Volume", false),
    FX_TRACK_5_SET_VOLUME(CommandCategory.FX_TRACK, "FX Track 5: Set Volume", false),
    FX_TRACK_6_SET_VOLUME(CommandCategory.FX_TRACK, "FX Track 6: Set Volume", false),
    FX_TRACK_7_SET_VOLUME(CommandCategory.FX_TRACK, "FX Track 7: Set Volume", false),
    FX_TRACK_8_SET_VOLUME(CommandCategory.FX_TRACK, "FX Track 8: Set Volume", false),
    FX_TRACK_1_SET_PANORAMA(CommandCategory.FX_TRACK, "FX Track 1: Set Panorama", false),
    FX_TRACK_2_SET_PANORAMA(CommandCategory.FX_TRACK, "FX Track 2: Set Panorama", false),
    FX_TRACK_3_SET_PANORAMA(CommandCategory.FX_TRACK, "FX Track 3: Set Panorama", false),
    FX_TRACK_4_SET_PANORAMA(CommandCategory.FX_TRACK, "FX Track 4: Set Panorama", false),
    FX_TRACK_5_SET_PANORAMA(CommandCategory.FX_TRACK, "FX Track 5: Set Panorama", false),
    FX_TRACK_6_SET_PANORAMA(CommandCategory.FX_TRACK, "FX Track 6: Set Panorama", false),
    FX_TRACK_7_SET_PANORAMA(CommandCategory.FX_TRACK, "FX Track 7: Set Panorama", false),
    FX_TRACK_8_SET_PANORAMA(CommandCategory.FX_TRACK, "FX Track 8: Set Panorama", false),
    FX_TRACK_1_TOGGLE_MUTE(CommandCategory.FX_TRACK, "FX Track 1: Toggle Mute", true),
    FX_TRACK_2_TOGGLE_MUTE(CommandCategory.FX_TRACK, "FX Track 2: Toggle Mute", true),
    FX_TRACK_3_TOGGLE_MUTE(CommandCategory.FX_TRACK, "FX Track 3: Toggle Mute", true),
    FX_TRACK_4_TOGGLE_MUTE(CommandCategory.FX_TRACK, "FX Track 4: Toggle Mute", true),
    FX_TRACK_5_TOGGLE_MUTE(CommandCategory.FX_TRACK, "FX Track 5: Toggle Mute", true),
    FX_TRACK_6_TOGGLE_MUTE(CommandCategory.FX_TRACK, "FX Track 6: Toggle Mute", true),
    FX_TRACK_7_TOGGLE_MUTE(CommandCategory.FX_TRACK, "FX Track 7: Toggle Mute", true),
    FX_TRACK_8_TOGGLE_MUTE(CommandCategory.FX_TRACK, "FX Track 8: Toggle Mute", true),
    FX_TRACK_1_SET_MUTE(CommandCategory.FX_TRACK, "FX Track 1: Set Mute", true),
    FX_TRACK_2_SET_MUTE(CommandCategory.FX_TRACK, "FX Track 2: Set Mute", true),
    FX_TRACK_3_SET_MUTE(CommandCategory.FX_TRACK, "FX Track 3: Set Mute", true),
    FX_TRACK_4_SET_MUTE(CommandCategory.FX_TRACK, "FX Track 4: Set Mute", true),
    FX_TRACK_5_SET_MUTE(CommandCategory.FX_TRACK, "FX Track 5: Set Mute", true),
    FX_TRACK_6_SET_MUTE(CommandCategory.FX_TRACK, "FX Track 6: Set Mute", true),
    FX_TRACK_7_SET_MUTE(CommandCategory.FX_TRACK, "FX Track 7: Set Mute", true),
    FX_TRACK_8_SET_MUTE(CommandCategory.FX_TRACK, "FX Track 8: Set Mute", true),
    FX_TRACK_1_TOGGLE_SOLO(CommandCategory.FX_TRACK, "FX Track 1: Toggle Solo", true),
    FX_TRACK_2_TOGGLE_SOLO(CommandCategory.FX_TRACK, "FX Track 2: Toggle Solo", true),
    FX_TRACK_3_TOGGLE_SOLO(CommandCategory.FX_TRACK, "FX Track 3: Toggle Solo", true),
    FX_TRACK_4_TOGGLE_SOLO(CommandCategory.FX_TRACK, "FX Track 4: Toggle Solo", true),
    FX_TRACK_5_TOGGLE_SOLO(CommandCategory.FX_TRACK, "FX Track 5: Toggle Solo", true),
    FX_TRACK_6_TOGGLE_SOLO(CommandCategory.FX_TRACK, "FX Track 6: Toggle Solo", true),
    FX_TRACK_7_TOGGLE_SOLO(CommandCategory.FX_TRACK, "FX Track 7: Toggle Solo", true),
    FX_TRACK_8_TOGGLE_SOLO(CommandCategory.FX_TRACK, "FX Track 8: Toggle Solo", true),
    FX_TRACK_1_SET_SOLO(CommandCategory.FX_TRACK, "FX Track 1: Set Solo", true),
    FX_TRACK_2_SET_SOLO(CommandCategory.FX_TRACK, "FX Track 2: Set Solo", true),
    FX_TRACK_3_SET_SOLO(CommandCategory.FX_TRACK, "FX Track 3: Set Solo", true),
    FX_TRACK_4_SET_SOLO(CommandCategory.FX_TRACK, "FX Track 4: Set Solo", true),
    FX_TRACK_5_SET_SOLO(CommandCategory.FX_TRACK, "FX Track 5: Set Solo", true),
    FX_TRACK_6_SET_SOLO(CommandCategory.FX_TRACK, "FX Track 6: Set Solo", true),
    FX_TRACK_7_SET_SOLO(CommandCategory.FX_TRACK, "FX Track 7: Set Solo", true),
    FX_TRACK_8_SET_SOLO(CommandCategory.FX_TRACK, "FX Track 8: Set Solo", true),
    FX_TRACK_1_TOGGLE_ARM(CommandCategory.FX_TRACK, "FX Track 1: Toggle Arm", true),
    FX_TRACK_2_TOGGLE_ARM(CommandCategory.FX_TRACK, "FX Track 2: Toggle Arm", true),
    FX_TRACK_3_TOGGLE_ARM(CommandCategory.FX_TRACK, "FX Track 3: Toggle Arm", true),
    FX_TRACK_4_TOGGLE_ARM(CommandCategory.FX_TRACK, "FX Track 4: Toggle Arm", true),
    FX_TRACK_5_TOGGLE_ARM(CommandCategory.FX_TRACK, "FX Track 5: Toggle Arm", true),
    FX_TRACK_6_TOGGLE_ARM(CommandCategory.FX_TRACK, "FX Track 6: Toggle Arm", true),
    FX_TRACK_7_TOGGLE_ARM(CommandCategory.FX_TRACK, "FX Track 7: Toggle Arm", true),
    FX_TRACK_8_TOGGLE_ARM(CommandCategory.FX_TRACK, "FX Track 8: Toggle Arm", true),
    FX_TRACK_1_SET_ARM(CommandCategory.FX_TRACK, "FX Track 1: Set Arm", true),
    FX_TRACK_2_SET_ARM(CommandCategory.FX_TRACK, "FX Track 2: Set Arm", true),
    FX_TRACK_3_SET_ARM(CommandCategory.FX_TRACK, "FX Track 3: Set Arm", true),
    FX_TRACK_4_SET_ARM(CommandCategory.FX_TRACK, "FX Track 4: Set Arm", true),
    FX_TRACK_5_SET_ARM(CommandCategory.FX_TRACK, "FX Track 5: Set Arm", true),
    FX_TRACK_6_SET_ARM(CommandCategory.FX_TRACK, "FX Track 6: Set Arm", true),
    FX_TRACK_7_SET_ARM(CommandCategory.FX_TRACK, "FX Track 7: Set Arm", true),
    FX_TRACK_8_SET_ARM(CommandCategory.FX_TRACK, "FX Track 8: Set Arm", true),
    FX_TRACK_1_TOGGLE_MONITOR(CommandCategory.FX_TRACK, "FX Track 1: Toggle Monitor", true),
    FX_TRACK_2_TOGGLE_MONITOR(CommandCategory.FX_TRACK, "FX Track 2: Toggle Monitor", true),
    FX_TRACK_3_TOGGLE_MONITOR(CommandCategory.FX_TRACK, "FX Track 3: Toggle Monitor", true),
    FX_TRACK_4_TOGGLE_MONITOR(CommandCategory.FX_TRACK, "FX Track 4: Toggle Monitor", true),
    FX_TRACK_5_TOGGLE_MONITOR(CommandCategory.FX_TRACK, "FX Track 5: Toggle Monitor", true),
    FX_TRACK_6_TOGGLE_MONITOR(CommandCategory.FX_TRACK, "FX Track 6: Toggle Monitor", true),
    FX_TRACK_7_TOGGLE_MONITOR(CommandCategory.FX_TRACK, "FX Track 7: Toggle Monitor", true),
    FX_TRACK_8_TOGGLE_MONITOR(CommandCategory.FX_TRACK, "FX Track 8: Toggle Monitor", true),
    FX_TRACK_1_SET_MONITOR(CommandCategory.FX_TRACK, "FX Track 1: Set Monitor", true),
    FX_TRACK_2_SET_MONITOR(CommandCategory.FX_TRACK, "FX Track 2: Set Monitor", true),
    FX_TRACK_3_SET_MONITOR(CommandCategory.FX_TRACK, "FX Track 3: Set Monitor", true),
    FX_TRACK_4_SET_MONITOR(CommandCategory.FX_TRACK, "FX Track 4: Set Monitor", true),
    FX_TRACK_5_SET_MONITOR(CommandCategory.FX_TRACK, "FX Track 5: Set Monitor", true),
    FX_TRACK_6_SET_MONITOR(CommandCategory.FX_TRACK, "FX Track 6: Set Monitor", true),
    FX_TRACK_7_SET_MONITOR(CommandCategory.FX_TRACK, "FX Track 7: Set Monitor", true),
    FX_TRACK_8_SET_MONITOR(CommandCategory.FX_TRACK, "FX Track 8: Set Monitor", true),
    FX_TRACK_1_TOGGLE_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 1: Toggle Auto Monitor", true),
    FX_TRACK_2_TOGGLE_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 2: Toggle Auto Monitor", true),
    FX_TRACK_3_TOGGLE_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 3: Toggle Auto Monitor", true),
    FX_TRACK_4_TOGGLE_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 4: Toggle Auto Monitor", true),
    FX_TRACK_5_TOGGLE_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 5: Toggle Auto Monitor", true),
    FX_TRACK_6_TOGGLE_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 6: Toggle Auto Monitor", true),
    FX_TRACK_7_TOGGLE_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 7: Toggle Auto Monitor", true),
    FX_TRACK_8_TOGGLE_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 8: Toggle Auto Monitor", true),
    FX_TRACK_1_SET_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 1: Set Auto Monitor", true),
    FX_TRACK_2_SET_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 2: Set Auto Monitor", true),
    FX_TRACK_3_SET_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 3: Set Auto Monitor", true),
    FX_TRACK_4_SET_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 4: Set Auto Monitor", true),
    FX_TRACK_5_SET_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 5: Set Auto Monitor", true),
    FX_TRACK_6_SET_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 6: Set Auto Monitor", true),
    FX_TRACK_7_SET_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 7: Set Auto Monitor", true),
    FX_TRACK_8_SET_AUTO_MONITOR(CommandCategory.FX_TRACK, "FX Track 8: Set Auto Monitor", true),

    MASTER_SET_VOLUME(CommandCategory.MASTER, "Master: Set Volume", false),
    MASTER_SET_PANORAMA(CommandCategory.MASTER, "Master: Set Panorama", false),
    MASTER_TOGGLE_MUTE(CommandCategory.MASTER, "Master: Toggle Mute", true),
    MASTER_SET_MUTE(CommandCategory.MASTER, "Master: Set Mute", true),
    MASTER_TOGGLE_SOLO(CommandCategory.MASTER, "Master: Toggle Solo", true),
    MASTER_SET_SOLO(CommandCategory.MASTER, "Master: Set Solo", true),
    MASTER_TOGGLE_ARM(CommandCategory.MASTER, "Master: Toggle Arm", true),
    MASTER_SET_ARM(CommandCategory.MASTER, "Master: Set Arm", true),
    MASTER_CROSSFADER(CommandCategory.MASTER, "Master: Crossfader", false),
    MASTER_SELECT(CommandCategory.MASTER, "Master: Select", true),

    DEVICE_TOGGLE_WINDOW(CommandCategory.DEVICE, "Device: Toggle Window", true),
    DEVICE_TOGGLE_BYPASS(CommandCategory.DEVICE, "Device: Bypass", true),
    DEVICE_TOGGLE_PIN(CommandCategory.DEVICE, "Device: Toggle Pin", true),
    DEVICE_TOGGLE_EXPAND(CommandCategory.DEVICE, "Device: Expand", true),
    DEVICE_TOGGLE_PARAMETERS(CommandCategory.DEVICE, "Device: Parameters", true),
    DEVICE_SELECT_PREVIOUS(CommandCategory.DEVICE, "Device: Select Previous", true),
    DEVICE_SELECT_NEXT(CommandCategory.DEVICE, "Device: Select Next", true),
    DEVICE_SCROLL_DEVICES(CommandCategory.DEVICE, "Device: Scroll devices", false),
    DEVICE_SELECT_PREVIOUS_PARAMETER_PAGE(CommandCategory.DEVICE, "Device: Select Previous Parameter Page", true),
    DEVICE_SELECT_NEXT_PARAMETER_PAGE(CommandCategory.DEVICE, "Device: Select Next Parameter Page", true),
    DEVICE_SELECT_PARAMETER_PAGE_1(CommandCategory.DEVICE, "Device: Select Parameter Page 1", true),
    DEVICE_SELECT_PARAMETER_PAGE_2(CommandCategory.DEVICE, "Device: Select Parameter Page 2", true),
    DEVICE_SELECT_PARAMETER_PAGE_3(CommandCategory.DEVICE, "Device: Select Parameter Page 3", true),
    DEVICE_SELECT_PARAMETER_PAGE_4(CommandCategory.DEVICE, "Device: Select Parameter Page 4", true),
    DEVICE_SELECT_PARAMETER_PAGE_5(CommandCategory.DEVICE, "Device: Select Parameter Page 5", true),
    DEVICE_SELECT_PARAMETER_PAGE_6(CommandCategory.DEVICE, "Device: Select Parameter Page 6", true),
    DEVICE_SELECT_PARAMETER_PAGE_7(CommandCategory.DEVICE, "Device: Select Parameter Page 7", true),
    DEVICE_SELECT_PARAMETER_PAGE_8(CommandCategory.DEVICE, "Device: Select Parameter Page 8", true),
    DEVICE_SCROLL_PARAMETER_PAGES(CommandCategory.DEVICE, "Device: Scroll Parameter Pages", false),
    DEVICE_SELECT_PREVIOUS_PARAMETER_BANK(CommandCategory.DEVICE, "Device: Select Previous Parameter Bank", true),
    DEVICE_SELECT_NEXT_PARAMETER_BANK(CommandCategory.DEVICE, "Device: Select Next Parameter Bank", true),
    DEVICE_SCROLL_PARAMETER_BANKS(CommandCategory.DEVICE, "Device: Scroll Parameter Banks", false),
    DEVICE_SET_PARAMETER_1(CommandCategory.DEVICE, "Device: Set Parameter 1", false),
    DEVICE_SET_PARAMETER_2(CommandCategory.DEVICE, "Device: Set Parameter 2", false),
    DEVICE_SET_PARAMETER_3(CommandCategory.DEVICE, "Device: Set Parameter 3", false),
    DEVICE_SET_PARAMETER_4(CommandCategory.DEVICE, "Device: Set Parameter 4", false),
    DEVICE_SET_PARAMETER_5(CommandCategory.DEVICE, "Device: Set Parameter 5", false),
    DEVICE_SET_PARAMETER_6(CommandCategory.DEVICE, "Device: Set Parameter 6", false),
    DEVICE_SET_PARAMETER_7(CommandCategory.DEVICE, "Device: Set Parameter 7", false),
    DEVICE_SET_PARAMETER_8(CommandCategory.DEVICE, "Device: Set Parameter 8", false),
    DEVICE_RESET_PARAMETER_1(CommandCategory.DEVICE, "Device: Reset Parameter 1", true),
    DEVICE_RESET_PARAMETER_2(CommandCategory.DEVICE, "Device: Reset Parameter 2", true),
    DEVICE_RESET_PARAMETER_3(CommandCategory.DEVICE, "Device: Reset Parameter 3", true),
    DEVICE_RESET_PARAMETER_4(CommandCategory.DEVICE, "Device: Reset Parameter 4", true),
    DEVICE_RESET_PARAMETER_5(CommandCategory.DEVICE, "Device: Reset Parameter 5", true),
    DEVICE_RESET_PARAMETER_6(CommandCategory.DEVICE, "Device: Reset Parameter 6", true),
    DEVICE_RESET_PARAMETER_7(CommandCategory.DEVICE, "Device: Reset Parameter 7", true),
    DEVICE_RESET_PARAMETER_8(CommandCategory.DEVICE, "Device: Reset Parameter 8", true),
    DEVICE_TOGGLE_PARAMETER_1(CommandCategory.DEVICE, "Device: Toggle Parameter 1", true),
    DEVICE_TOGGLE_PARAMETER_2(CommandCategory.DEVICE, "Device: Toggle Parameter 2", true),
    DEVICE_TOGGLE_PARAMETER_3(CommandCategory.DEVICE, "Device: Toggle Parameter 3", true),
    DEVICE_TOGGLE_PARAMETER_4(CommandCategory.DEVICE, "Device: Toggle Parameter 4", true),
    DEVICE_TOGGLE_PARAMETER_5(CommandCategory.DEVICE, "Device: Toggle Parameter 5", true),
    DEVICE_TOGGLE_PARAMETER_6(CommandCategory.DEVICE, "Device: Toggle Parameter 6", true),
    DEVICE_TOGGLE_PARAMETER_7(CommandCategory.DEVICE, "Device: Toggle Parameter 7", true),
    DEVICE_TOGGLE_PARAMETER_8(CommandCategory.DEVICE, "Device: Toggle Parameter 8", true),

    LAYER_SELECT_PREVIOUS_BANK_PAGE(CommandCategory.LAYER, "Layer: Select Previous Bank Page", true),
    LAYER_SELECT_NEXT_BANK_PAGE(CommandCategory.LAYER, "Layer: Select Next Bank Page", true),
    LAYER_SELECT_PREVIOUS_LAYER(CommandCategory.LAYER, "Layer: Select Previous Layer", true),
    LAYER_SELECT_NEXT_LAYER(CommandCategory.LAYER, "Layer: Select Next Layer", true),
    LAYER_SCROLL_LAYERS(CommandCategory.LAYER, "Layer: Scroll Layers", false),
    LAYER_1_SELECT(CommandCategory.LAYER, "Layer 1: Select", true),
    LAYER_2_SELECT(CommandCategory.LAYER, "Layer 2: Select", true),
    LAYER_3_SELECT(CommandCategory.LAYER, "Layer 3: Select", true),
    LAYER_4_SELECT(CommandCategory.LAYER, "Layer 4: Select", true),
    LAYER_5_SELECT(CommandCategory.LAYER, "Layer 5: Select", true),
    LAYER_6_SELECT(CommandCategory.LAYER, "Layer 6: Select", true),
    LAYER_7_SELECT(CommandCategory.LAYER, "Layer 7: Select", true),
    LAYER_8_SELECT(CommandCategory.LAYER, "Layer 8: Select", true),
    LAYER_1_TOGGLE_ACTIVE(CommandCategory.LAYER, "Layer 1: Toggle Active", true),
    LAYER_2_TOGGLE_ACTIVE(CommandCategory.LAYER, "Layer 2: Toggle Active", true),
    LAYER_3_TOGGLE_ACTIVE(CommandCategory.LAYER, "Layer 3: Toggle Active", true),
    LAYER_4_TOGGLE_ACTIVE(CommandCategory.LAYER, "Layer 4: Toggle Active", true),
    LAYER_5_TOGGLE_ACTIVE(CommandCategory.LAYER, "Layer 5: Toggle Active", true),
    LAYER_6_TOGGLE_ACTIVE(CommandCategory.LAYER, "Layer 6: Toggle Active", true),
    LAYER_7_TOGGLE_ACTIVE(CommandCategory.LAYER, "Layer 7: Toggle Active", true),
    LAYER_8_TOGGLE_ACTIVE(CommandCategory.LAYER, "Layer 8: Toggle Active", true),
    LAYER_SELECTED_TOGGLE_ACTIVE(CommandCategory.LAYER, "Layer Selected: Toggle Active", true),
    LAYER_1_SET_ACTIVE(CommandCategory.LAYER, "Layer 1: Set Active", true),
    LAYER_2_SET_ACTIVE(CommandCategory.LAYER, "Layer 2: Set Active", true),
    LAYER_3_SET_ACTIVE(CommandCategory.LAYER, "Layer 3: Set Active", true),
    LAYER_4_SET_ACTIVE(CommandCategory.LAYER, "Layer 4: Set Active", true),
    LAYER_5_SET_ACTIVE(CommandCategory.LAYER, "Layer 5: Set Active", true),
    LAYER_6_SET_ACTIVE(CommandCategory.LAYER, "Layer 6: Set Active", true),
    LAYER_7_SET_ACTIVE(CommandCategory.LAYER, "Layer 7: Set Active", true),
    LAYER_8_SET_ACTIVE(CommandCategory.LAYER, "Layer 8: Set Active", true),
    LAYER_SELECTED_SET_ACTIVE(CommandCategory.LAYER, "Layer Selected: Set Active", true),
    LAYER_1_SET_VOLUME(CommandCategory.LAYER, "Layer 1: Set Volume", false),
    LAYER_2_SET_VOLUME(CommandCategory.LAYER, "Layer 2: Set Volume", false),
    LAYER_3_SET_VOLUME(CommandCategory.LAYER, "Layer 3: Set Volume", false),
    LAYER_4_SET_VOLUME(CommandCategory.LAYER, "Layer 4: Set Volume", false),
    LAYER_5_SET_VOLUME(CommandCategory.LAYER, "Layer 5: Set Volume", false),
    LAYER_6_SET_VOLUME(CommandCategory.LAYER, "Layer 6: Set Volume", false),
    LAYER_7_SET_VOLUME(CommandCategory.LAYER, "Layer 7: Set Volume", false),
    LAYER_8_SET_VOLUME(CommandCategory.LAYER, "Layer 8: Set Volume", false),
    LAYER_SELECTED_SET_VOLUME_LAYER(CommandCategory.LAYER, "Layer Selected: Set Volume Layer", false),
    LAYER_1_SET_PANORAMA(CommandCategory.LAYER, "Layer 1: Set Panorama", false),
    LAYER_2_SET_PANORAMA(CommandCategory.LAYER, "Layer 2: Set Panorama", false),
    LAYER_3_SET_PANORAMA(CommandCategory.LAYER, "Layer 3: Set Panorama", false),
    LAYER_4_SET_PANORAMA(CommandCategory.LAYER, "Layer 4: Set Panorama", false),
    LAYER_5_SET_PANORAMA(CommandCategory.LAYER, "Layer 5: Set Panorama", false),
    LAYER_6_SET_PANORAMA(CommandCategory.LAYER, "Layer 6: Set Panorama", false),
    LAYER_7_SET_PANORAMA(CommandCategory.LAYER, "Layer 7: Set Panorama", false),
    LAYER_8_SET_PANORAMA(CommandCategory.LAYER, "Layer 8: Set Panorama", false),
    LAYER_SELECTED_SET_PANORAMA(CommandCategory.LAYER, "Layer Selected: Set Panorama", false),
    LAYER_1_TOGGLE_MUTE(CommandCategory.LAYER, "Layer 1: Toggle Mute", true),
    LAYER_2_TOGGLE_MUTE(CommandCategory.LAYER, "Layer 2: Toggle Mute", true),
    LAYER_3_TOGGLE_MUTE(CommandCategory.LAYER, "Layer 3: Toggle Mute", true),
    LAYER_4_TOGGLE_MUTE(CommandCategory.LAYER, "Layer 4: Toggle Mute", true),
    LAYER_5_TOGGLE_MUTE(CommandCategory.LAYER, "Layer 5: Toggle Mute", true),
    LAYER_6_TOGGLE_MUTE(CommandCategory.LAYER, "Layer 6: Toggle Mute", true),
    LAYER_7_TOGGLE_MUTE(CommandCategory.LAYER, "Layer 7: Toggle Mute", true),
    LAYER_8_TOGGLE_MUTE(CommandCategory.LAYER, "Layer 8: Toggle Mute", true),
    LAYER_SELECTED_TOGGLE_MUTE(CommandCategory.LAYER, "Layer Selected: Toggle Mute", true),
    LAYER_1_SET_MUTE(CommandCategory.LAYER, "Layer 1: Set Mute", true),
    LAYER_2_SET_MUTE(CommandCategory.LAYER, "Layer 2: Set Mute", true),
    LAYER_3_SET_MUTE(CommandCategory.LAYER, "Layer 3: Set Mute", true),
    LAYER_4_SET_MUTE(CommandCategory.LAYER, "Layer 4: Set Mute", true),
    LAYER_5_SET_MUTE(CommandCategory.LAYER, "Layer 5: Set Mute", true),
    LAYER_6_SET_MUTE(CommandCategory.LAYER, "Layer 6: Set Mute", true),
    LAYER_7_SET_MUTE(CommandCategory.LAYER, "Layer 7: Set Mute", true),
    LAYER_8_SET_MUTE(CommandCategory.LAYER, "Layer 8: Set Mute", true),
    LAYER_SELECTED_SET_MUTE(CommandCategory.LAYER, "Layer Selected: Set Mute", true),
    LAYER_1_TOGGLE_SOLO(CommandCategory.LAYER, "Layer 1: Toggle Solo", true),
    LAYER_2_TOGGLE_SOLO(CommandCategory.LAYER, "Layer 2: Toggle Solo", true),
    LAYER_3_TOGGLE_SOLO(CommandCategory.LAYER, "Layer 3: Toggle Solo", true),
    LAYER_4_TOGGLE_SOLO(CommandCategory.LAYER, "Layer 4: Toggle Solo", true),
    LAYER_5_TOGGLE_SOLO(CommandCategory.LAYER, "Layer 5: Toggle Solo", true),
    LAYER_6_TOGGLE_SOLO(CommandCategory.LAYER, "Layer 6: Toggle Solo", true),
    LAYER_7_TOGGLE_SOLO(CommandCategory.LAYER, "Layer 7: Toggle Solo", true),
    LAYER_8_TOGGLE_SOLO(CommandCategory.LAYER, "Layer 8: Toggle Solo", true),
    LAYER_SELECTED_TOGGLE_SOLO(CommandCategory.LAYER, "Layer Selected: Toggle Solo", true),
    LAYER_1_SET_SOLO(CommandCategory.LAYER, "Layer 1: Set Solo", true),
    LAYER_2_SET_SOLO(CommandCategory.LAYER, "Layer 2: Set Solo", true),
    LAYER_3_SET_SOLO(CommandCategory.LAYER, "Layer 3: Set Solo", true),
    LAYER_4_SET_SOLO(CommandCategory.LAYER, "Layer 4: Set Solo", true),
    LAYER_5_SET_SOLO(CommandCategory.LAYER, "Layer 5: Set Solo", true),
    LAYER_6_SET_SOLO(CommandCategory.LAYER, "Layer 6: Set Solo", true),
    LAYER_7_SET_SOLO(CommandCategory.LAYER, "Layer 7: Set Solo", true),
    LAYER_8_SET_SOLO(CommandCategory.LAYER, "Layer 8: Set Solo", true),
    LAYER_SELECTED_SET_SOLO(CommandCategory.LAYER, "Layer Selected: Set Solo", true),
    LAYER_1_SET_SEND_1(CommandCategory.LAYER, "Layer 1: Set Send 1", false),
    LAYER_2_SET_SEND_1(CommandCategory.LAYER, "Layer 2: Set Send 1", false),
    LAYER_3_SET_SEND_1(CommandCategory.LAYER, "Layer 3: Set Send 1", false),
    LAYER_4_SET_SEND_1(CommandCategory.LAYER, "Layer 4: Set Send 1", false),
    LAYER_5_SET_SEND_1(CommandCategory.LAYER, "Layer 5: Set Send 1", false),
    LAYER_6_SET_SEND_1(CommandCategory.LAYER, "Layer 6: Set Send 1", false),
    LAYER_7_SET_SEND_1(CommandCategory.LAYER, "Layer 7: Set Send 1", false),
    LAYER_8_SET_SEND_1(CommandCategory.LAYER, "Layer 8: Set Send 1", false),
    LAYER_1_SET_SEND_2(CommandCategory.LAYER, "Layer 1: Set Send 2", false),
    LAYER_2_SET_SEND_2(CommandCategory.LAYER, "Layer 2: Set Send 2", false),
    LAYER_3_SET_SEND_2(CommandCategory.LAYER, "Layer 3: Set Send 2", false),
    LAYER_4_SET_SEND_2(CommandCategory.LAYER, "Layer 4: Set Send 2", false),
    LAYER_5_SET_SEND_2(CommandCategory.LAYER, "Layer 5: Set Send 2", false),
    LAYER_6_SET_SEND_2(CommandCategory.LAYER, "Layer 6: Set Send 2", false),
    LAYER_7_SET_SEND_2(CommandCategory.LAYER, "Layer 7: Set Send 2", false),
    LAYER_8_SET_SEND_2(CommandCategory.LAYER, "Layer 8: Set Send 2", false),
    LAYER_1_SET_SEND_3(CommandCategory.LAYER, "Layer 1: Set Send 3", false),
    LAYER_2_SET_SEND_3(CommandCategory.LAYER, "Layer 2: Set Send 3", false),
    LAYER_3_SET_SEND_3(CommandCategory.LAYER, "Layer 3: Set Send 3", false),
    LAYER_4_SET_SEND_3(CommandCategory.LAYER, "Layer 4: Set Send 3", false),
    LAYER_5_SET_SEND_3(CommandCategory.LAYER, "Layer 5: Set Send 3", false),
    LAYER_6_SET_SEND_3(CommandCategory.LAYER, "Layer 6: Set Send 3", false),
    LAYER_7_SET_SEND_3(CommandCategory.LAYER, "Layer 7: Set Send 3", false),
    LAYER_8_SET_SEND_3(CommandCategory.LAYER, "Layer 8: Set Send 3", false),
    LAYER_1_SET_SEND_4(CommandCategory.LAYER, "Layer 1: Set Send 4", false),
    LAYER_2_SET_SEND_4(CommandCategory.LAYER, "Layer 2: Set Send 4", false),
    LAYER_3_SET_SEND_4(CommandCategory.LAYER, "Layer 3: Set Send 4", false),
    LAYER_4_SET_SEND_4(CommandCategory.LAYER, "Layer 4: Set Send 4", false),
    LAYER_5_SET_SEND_4(CommandCategory.LAYER, "Layer 5: Set Send 4", false),
    LAYER_6_SET_SEND_4(CommandCategory.LAYER, "Layer 6: Set Send 4", false),
    LAYER_7_SET_SEND_4(CommandCategory.LAYER, "Layer 7: Set Send 4", false),
    LAYER_8_SET_SEND_4(CommandCategory.LAYER, "Layer 8: Set Send 4", false),
    LAYER_1_SET_SEND_5(CommandCategory.LAYER, "Layer 1: Set Send 5", false),
    LAYER_2_SET_SEND_5(CommandCategory.LAYER, "Layer 2: Set Send 5", false),
    LAYER_3_SET_SEND_5(CommandCategory.LAYER, "Layer 3: Set Send 5", false),
    LAYER_4_SET_SEND_5(CommandCategory.LAYER, "Layer 4: Set Send 5", false),
    LAYER_5_SET_SEND_5(CommandCategory.LAYER, "Layer 5: Set Send 5", false),
    LAYER_6_SET_SEND_5(CommandCategory.LAYER, "Layer 6: Set Send 5", false),
    LAYER_7_SET_SEND_5(CommandCategory.LAYER, "Layer 7: Set Send 5", false),
    LAYER_8_SET_SEND_5(CommandCategory.LAYER, "Layer 8: Set Send 5", false),
    LAYER_1_SET_SEND_6(CommandCategory.LAYER, "Layer 1: Set Send 6", false),
    LAYER_2_SET_SEND_6(CommandCategory.LAYER, "Layer 2: Set Send 6", false),
    LAYER_3_SET_SEND_6(CommandCategory.LAYER, "Layer 3: Set Send 6", false),
    LAYER_4_SET_SEND_6(CommandCategory.LAYER, "Layer 4: Set Send 6", false),
    LAYER_5_SET_SEND_6(CommandCategory.LAYER, "Layer 5: Set Send 6", false),
    LAYER_6_SET_SEND_6(CommandCategory.LAYER, "Layer 6: Set Send 6", false),
    LAYER_7_SET_SEND_6(CommandCategory.LAYER, "Layer 7: Set Send 6", false),
    LAYER_8_SET_SEND_6(CommandCategory.LAYER, "Layer 8: Set Send 6", false),
    LAYER_1_SET_SEND_7(CommandCategory.LAYER, "Layer 1: Set Send 7", false),
    LAYER_2_SET_SEND_7(CommandCategory.LAYER, "Layer 2: Set Send 7", false),
    LAYER_3_SET_SEND_7(CommandCategory.LAYER, "Layer 3: Set Send 7", false),
    LAYER_4_SET_SEND_7(CommandCategory.LAYER, "Layer 4: Set Send 7", false),
    LAYER_5_SET_SEND_7(CommandCategory.LAYER, "Layer 5: Set Send 7", false),
    LAYER_6_SET_SEND_7(CommandCategory.LAYER, "Layer 6: Set Send 7", false),
    LAYER_7_SET_SEND_7(CommandCategory.LAYER, "Layer 7: Set Send 7", false),
    LAYER_8_SET_SEND_7(CommandCategory.LAYER, "Layer 8: Set Send 7", false),
    LAYER_1_SET_SEND_8(CommandCategory.LAYER, "Layer 1: Set Send 8", false),
    LAYER_2_SET_SEND_8(CommandCategory.LAYER, "Layer 2: Set Send 8", false),
    LAYER_3_SET_SEND_8(CommandCategory.LAYER, "Layer 3: Set Send 8", false),
    LAYER_4_SET_SEND_8(CommandCategory.LAYER, "Layer 4: Set Send 8", false),
    LAYER_5_SET_SEND_8(CommandCategory.LAYER, "Layer 5: Set Send 8", false),
    LAYER_6_SET_SEND_8(CommandCategory.LAYER, "Layer 6: Set Send 8", false),
    LAYER_7_SET_SEND_8(CommandCategory.LAYER, "Layer 7: Set Send 8", false),
    LAYER_8_SET_SEND_8(CommandCategory.LAYER, "Layer 8: Set Send 8", false),
    LAYER_SELECTED_SET_SEND_1(CommandCategory.LAYER, "Layer Selected: Set Send 1", false),
    LAYER_SELECTED_SET_SEND_2(CommandCategory.LAYER, "Layer Selected: Set Send 2", false),
    LAYER_SELECTED_SET_SEND_3(CommandCategory.LAYER, "Layer Selected: Set Send 3", false),
    LAYER_SELECTED_SET_SEND_4(CommandCategory.LAYER, "Layer Selected: Set Send 4", false),
    LAYER_SELECTED_SET_SEND_5(CommandCategory.LAYER, "Layer Selected: Set Send 5", false),
    LAYER_SELECTED_SET_SEND_6(CommandCategory.LAYER, "Layer Selected: Set Send 6", false),
    LAYER_SELECTED_SET_SEND_7(CommandCategory.LAYER, "Layer Selected: Set Send 7", false),
    LAYER_SELECTED_SET_SEND_8(CommandCategory.LAYER, "Layer Selected: Set Send 8", false),

    EQ_SET_TYPE_1(CommandCategory.EQ, "EQ: Set Type 1", false),
    EQ_SET_TYPE_2(CommandCategory.EQ, "EQ: Set Type 2", false),
    EQ_SET_TYPE_3(CommandCategory.EQ, "EQ: Set Type 3", false),
    EQ_SET_TYPE_4(CommandCategory.EQ, "EQ: Set Type 4", false),
    EQ_SET_TYPE_5(CommandCategory.EQ, "EQ: Set Type 5", false),
    EQ_SET_TYPE_6(CommandCategory.EQ, "EQ: Set Type 6", false),
    EQ_SET_TYPE_7(CommandCategory.EQ, "EQ: Set Type 7", false),
    EQ_SET_TYPE_8(CommandCategory.EQ, "EQ: Set Type 8", false),
    EQ_SET_FREQ_1(CommandCategory.EQ, "EQ: Set Freq 1", false),
    EQ_SET_FREQ_2(CommandCategory.EQ, "EQ: Set Freq 2", false),
    EQ_SET_FREQ_3(CommandCategory.EQ, "EQ: Set Freq 3", false),
    EQ_SET_FREQ_4(CommandCategory.EQ, "EQ: Set Freq 4", false),
    EQ_SET_FREQ_5(CommandCategory.EQ, "EQ: Set Freq 5", false),
    EQ_SET_FREQ_6(CommandCategory.EQ, "EQ: Set Freq 6", false),
    EQ_SET_FREQ_7(CommandCategory.EQ, "EQ: Set Freq 7", false),
    EQ_SET_FREQ_8(CommandCategory.EQ, "EQ: Set Freq 8", false),
    EQ_SET_GAIN_1(CommandCategory.EQ, "EQ: Set Gain 1", false),
    EQ_SET_GAIN_2(CommandCategory.EQ, "EQ: Set Gain 2", false),
    EQ_SET_GAIN_3(CommandCategory.EQ, "EQ: Set Gain 3", false),
    EQ_SET_GAIN_4(CommandCategory.EQ, "EQ: Set Gain 4", false),
    EQ_SET_GAIN_5(CommandCategory.EQ, "EQ: Set Gain 5", false),
    EQ_SET_GAIN_6(CommandCategory.EQ, "EQ: Set Gain 6", false),
    EQ_SET_GAIN_7(CommandCategory.EQ, "EQ: Set Gain 7", false),
    EQ_SET_GAIN_8(CommandCategory.EQ, "EQ: Set Gain 8", false),
    EQ_SET_Q_1(CommandCategory.EQ, "EQ: Set Q 1", false),
    EQ_SET_Q_2(CommandCategory.EQ, "EQ: Set Q 2", false),
    EQ_SET_Q_3(CommandCategory.EQ, "EQ: Set Q 3", false),
    EQ_SET_Q_4(CommandCategory.EQ, "EQ: Set Q 4", false),
    EQ_SET_Q_5(CommandCategory.EQ, "EQ: Set Q 5", false),
    EQ_SET_Q_6(CommandCategory.EQ, "EQ: Set Q 6", false),
    EQ_SET_Q_7(CommandCategory.EQ, "EQ: Set Q 7", false),
    EQ_SET_Q_8(CommandCategory.EQ, "EQ: Set Q 8", false),

    BROWSER_BROWSE_PRESETS(CommandCategory.BROWSER, "Browser: Browse Presets", true),
    BROWSER_INSERT_DEVICE_BEFORE_CURRENT(CommandCategory.BROWSER, "Browser: Insert Device before current", true),
    BROWSER_INSERT_DEVICE_AFTER_CURRENT(CommandCategory.BROWSER, "Browser: Insert Device after current", true),
    BROWSER_COMMIT_SELECTION(CommandCategory.BROWSER, "Browser: Commit Selection", true),
    BROWSER_CANCEL_SELECTION(CommandCategory.BROWSER, "Browser: Cancel Selection", true),
    BROWSER_SELECT_PREVIOUS_FILTER_IN_COLUMN_1(CommandCategory.BROWSER, "Browser: Select Previous Filter in Column 1", true),
    BROWSER_SELECT_PREVIOUS_FILTER_IN_COLUMN_2(CommandCategory.BROWSER, "Browser: Select Previous Filter in Column 2", true),
    BROWSER_SELECT_PREVIOUS_FILTER_IN_COLUMN_3(CommandCategory.BROWSER, "Browser: Select Previous Filter in Column 3", true),
    BROWSER_SELECT_PREVIOUS_FILTER_IN_COLUMN_4(CommandCategory.BROWSER, "Browser: Select Previous Filter in Column 4", true),
    BROWSER_SELECT_PREVIOUS_FILTER_IN_COLUMN_5(CommandCategory.BROWSER, "Browser: Select Previous Filter in Column 5", true),
    BROWSER_SELECT_PREVIOUS_FILTER_IN_COLUMN_6(CommandCategory.BROWSER, "Browser: Select Previous Filter in Column 6", true),
    BROWSER_SELECT_PREVIOUS_FILTER_IN_COLUMN_7(CommandCategory.BROWSER, "Browser: Select Previous Filter in Column 7", true),
    BROWSER_SELECT_PREVIOUS_FILTER_IN_COLUMN_8(CommandCategory.BROWSER, "Browser: Select Previous Filter in Column 8", true),
    BROWSER_SELECT_NEXT_FILTER_IN_COLUMN_1(CommandCategory.BROWSER, "Browser: Select Next Filter in Column 1", true),
    BROWSER_SELECT_NEXT_FILTER_IN_COLUMN_2(CommandCategory.BROWSER, "Browser: Select Next Filter in Column 2", true),
    BROWSER_SELECT_NEXT_FILTER_IN_COLUMN_3(CommandCategory.BROWSER, "Browser: Select Next Filter in Column 3", true),
    BROWSER_SELECT_NEXT_FILTER_IN_COLUMN_4(CommandCategory.BROWSER, "Browser: Select Next Filter in Column 4", true),
    BROWSER_SELECT_NEXT_FILTER_IN_COLUMN_5(CommandCategory.BROWSER, "Browser: Select Next Filter in Column 5", true),
    BROWSER_SELECT_NEXT_FILTER_IN_COLUMN_6(CommandCategory.BROWSER, "Browser: Select Next Filter in Column 6", true),
    BROWSER_SELECT_NEXT_FILTER_IN_COLUMN_7(CommandCategory.BROWSER, "Browser: Select Next Filter in Column 7", true),
    BROWSER_SELECT_NEXT_FILTER_IN_COLUMN_8(CommandCategory.BROWSER, "Browser: Select Next Filter in Column 8", true),
    BROWSER_SCROLL_FILTER_IN_COLUMN_1(CommandCategory.BROWSER, "Browser: Scroll Filter in Column 1", false),
    BROWSER_SCROLL_FILTER_IN_COLUMN_2(CommandCategory.BROWSER, "Browser: Scroll Filter in Column 2", false),
    BROWSER_SCROLL_FILTER_IN_COLUMN_3(CommandCategory.BROWSER, "Browser: Scroll Filter in Column 3", false),
    BROWSER_SCROLL_FILTER_IN_COLUMN_4(CommandCategory.BROWSER, "Browser: Scroll Filter in Column 4", false),
    BROWSER_SCROLL_FILTER_IN_COLUMN_5(CommandCategory.BROWSER, "Browser: Scroll Filter in Column 5", false),
    BROWSER_SCROLL_FILTER_IN_COLUMN_6(CommandCategory.BROWSER, "Browser: Scroll Filter in Column 6", false),
    BROWSER_SCROLL_FILTER_IN_COLUMN_7(CommandCategory.BROWSER, "Browser: Scroll Filter in Column 7", false),
    BROWSER_SCROLL_FILTER_IN_COLUMN_8(CommandCategory.BROWSER, "Browser: Scroll Filter in Column 8", false),
    BROWSER_RESET_FILTER_COLUMN_1(CommandCategory.BROWSER, "Browser: Reset Filter Column 1", true),
    BROWSER_RESET_FILTER_COLUMN_2(CommandCategory.BROWSER, "Browser: Reset Filter Column 2", true),
    BROWSER_RESET_FILTER_COLUMN_3(CommandCategory.BROWSER, "Browser: Reset Filter Column 3", true),
    BROWSER_RESET_FILTER_COLUMN_4(CommandCategory.BROWSER, "Browser: Reset Filter Column 4", true),
    BROWSER_RESET_FILTER_COLUMN_5(CommandCategory.BROWSER, "Browser: Reset Filter Column 5", true),
    BROWSER_RESET_FILTER_COLUMN_6(CommandCategory.BROWSER, "Browser: Reset Filter Column 6", true),
    BROWSER_RESET_FILTER_COLUMN_7(CommandCategory.BROWSER, "Browser: Reset Filter Column 7", true),
    BROWSER_RESET_FILTER_COLUMN_8(CommandCategory.BROWSER, "Browser: Reset Filter Column 8", true),
    BROWSER_SELECT_THE_PREVIOUS_PRESET(CommandCategory.BROWSER, "Browser: Select the previous preset", true),
    BROWSER_SELECT_THE_NEXT_PRESET(CommandCategory.BROWSER, "Browser: Select the next preset", true),
    BROWSER_SCROLL_PRESETS(CommandCategory.BROWSER, "Browser: Scroll presets", false),
    BROWSER_SELECT_THE_PREVIOUS_TAB(CommandCategory.BROWSER, "Browser: Select the previous tab", true),
    BROWSER_SELECT_THE_NEXT_TAB(CommandCategory.BROWSER, "Browser: Select the next tab", true),
    BROWSER_SCROLL_TABS(CommandCategory.BROWSER, "Browser: Scroll tabs", false),

    SCENE_1_LAUNCH_SCENE(CommandCategory.SCENE, "Scene 1: Launch Scene", true),
    SCENE_2_LAUNCH_SCENE(CommandCategory.SCENE, "Scene 2: Launch Scene", true),
    SCENE_3_LAUNCH_SCENE(CommandCategory.SCENE, "Scene 3: Launch Scene", true),
    SCENE_4_LAUNCH_SCENE(CommandCategory.SCENE, "Scene 4: Launch Scene", true),
    SCENE_5_LAUNCH_SCENE(CommandCategory.SCENE, "Scene 5: Launch Scene", true),
    SCENE_6_LAUNCH_SCENE(CommandCategory.SCENE, "Scene 6: Launch Scene", true),
    SCENE_7_LAUNCH_SCENE(CommandCategory.SCENE, "Scene 7: Launch Scene", true),
    SCENE_8_LAUNCH_SCENE(CommandCategory.SCENE, "Scene 8: Launch Scene", true),
    SCENE_1_LAUNCH_ALT_SCENE(CommandCategory.SCENE, "Scene 1: Launch Scene Alternative", true),
    SCENE_2_LAUNCH_ALT_SCENE(CommandCategory.SCENE, "Scene 2: Launch Scene Alternative", true),
    SCENE_3_LAUNCH_ALT_SCENE(CommandCategory.SCENE, "Scene 3: Launch Scene Alternative", true),
    SCENE_4_LAUNCH_ALT_SCENE(CommandCategory.SCENE, "Scene 4: Launch Scene Alternative", true),
    SCENE_5_LAUNCH_ALT_SCENE(CommandCategory.SCENE, "Scene 5: Launch Scene Alternative", true),
    SCENE_6_LAUNCH_ALT_SCENE(CommandCategory.SCENE, "Scene 6: Launch Scene Alternative", true),
    SCENE_7_LAUNCH_ALT_SCENE(CommandCategory.SCENE, "Scene 7: Launch Scene Alternative", true),
    SCENE_8_LAUNCH_ALT_SCENE(CommandCategory.SCENE, "Scene 8: Launch Scene Alternative", true),
    SCENE_SELECT_PREVIOUS_BANK(CommandCategory.SCENE, "Scene: Select Previous Bank", true),
    SCENE_SELECT_NEXT_BANK(CommandCategory.SCENE, "Scene: Select Next Bank", true),
    SCENE_CREATE_SCENE(CommandCategory.SCENE, "Scene: Create Scene", true),
    SCENE_CREATE_SCENE_FROM_PLAYING_CLIPS(CommandCategory.SCENE, "Scene: Create Scene from playing Clips", true),

    CLIP_TOGGLE_PIN(CommandCategory.CLIP, "Clip: Toggle Pin", true),
    CLIP_PREVIOUS(CommandCategory.CLIP, "Clip: Select previous", true),
    CLIP_NEXT(CommandCategory.CLIP, "Clip: Select next", true),
    CLIP_SCROLL(CommandCategory.CLIP, "Clip: Scroll clips", false),
    CLIP_PLAY(CommandCategory.CLIP, "Clip: Play", true),
    CLIP_PLAY_ALT(CommandCategory.CLIP, "Clip: Play Alternative", true),
    CLIP_STOP(CommandCategory.CLIP, "Clip: Stop", true),
    CLIP_RECORD(CommandCategory.CLIP, "Clip: Record", true),
    CLIP_NEW(CommandCategory.CLIP, "Clip: New", true),
    CLIP_QUANTIZE(CommandCategory.CLIP, "Clip: Quantize", true),

    MARKER_1_LAUNCH_MARKER(CommandCategory.MARKER, "Marker 1: Launch Marker", true),
    MARKER_2_LAUNCH_MARKER(CommandCategory.MARKER, "Marker 2: Launch Marker", true),
    MARKER_3_LAUNCH_MARKER(CommandCategory.MARKER, "Marker 3: Launch Marker", true),
    MARKER_4_LAUNCH_MARKER(CommandCategory.MARKER, "Marker 4: Launch Marker", true),
    MARKER_5_LAUNCH_MARKER(CommandCategory.MARKER, "Marker 5: Launch Marker", true),
    MARKER_6_LAUNCH_MARKER(CommandCategory.MARKER, "Marker 6: Launch Marker", true),
    MARKER_7_LAUNCH_MARKER(CommandCategory.MARKER, "Marker 7: Launch Marker", true),
    MARKER_8_LAUNCH_MARKER(CommandCategory.MARKER, "Marker 8: Launch Marker", true),
    MARKER_SELECT_PREVIOUS_BANK(CommandCategory.MARKER, "Marker: Select Previous Bank", true),
    MARKER_SELECT_NEXT_BANK(CommandCategory.MARKER, "Marker: Select Next Bank", true),

    MODES_KNOB1(CommandCategory.MODES, "Modes: Item 1: Set value", false),
    MODES_KNOB2(CommandCategory.MODES, "Modes: Item 2: Set value", false),
    MODES_KNOB3(CommandCategory.MODES, "Modes: Item 3: Set value", false),
    MODES_KNOB4(CommandCategory.MODES, "Modes: Item 4: Set value", false),
    MODES_KNOB5(CommandCategory.MODES, "Modes: Item 5: Set value", false),
    MODES_KNOB6(CommandCategory.MODES, "Modes: Item 6: Set value", false),
    MODES_KNOB7(CommandCategory.MODES, "Modes: Item 7: Set value", false),
    MODES_KNOB8(CommandCategory.MODES, "Modes: Item 8: Set value", false),
    MODES_BUTTON1(CommandCategory.MODES, "Modes: Item 1: Select", true),
    MODES_BUTTON2(CommandCategory.MODES, "Modes: Item 2: Select", true),
    MODES_BUTTON3(CommandCategory.MODES, "Modes: Item 3: Select", true),
    MODES_BUTTON4(CommandCategory.MODES, "Modes: Item 4: Select", true),
    MODES_BUTTON5(CommandCategory.MODES, "Modes: Item 5: Select", true),
    MODES_BUTTON6(CommandCategory.MODES, "Modes: Item 6: Select", true),
    MODES_BUTTON7(CommandCategory.MODES, "Modes: Item 7: Select", true),
    MODES_BUTTON8(CommandCategory.MODES, "Modes: Item 8: Select", true),
    MODES_NEXT_ITEM(CommandCategory.MODES, "Modes: Select Next Item", true),
    MODES_PREV_ITEM(CommandCategory.MODES, "Modes: Select Previous Item", true),
    MODES_NEXT_PAGE(CommandCategory.MODES, "Modes: Select Next Item Page", true),
    MODES_PREV_PAGE(CommandCategory.MODES, "Modes: Select Previous Item Page", true),
    MODES_SELECT_MODE_TRACK(CommandCategory.MODES, "Modes: Select Track Mode", true),
    MODES_SELECT_MODE_VOLUME(CommandCategory.MODES, "Modes: Select Volume Mode", true),
    MODES_SELECT_MODE_PAN(CommandCategory.MODES, "Modes: Select Panorama Mode", true),
    MODES_SELECT_MODE_SEND1(CommandCategory.MODES, "Modes: Select Send 1 Mode", true),
    MODES_SELECT_MODE_SEND2(CommandCategory.MODES, "Modes: Select Send 2 Mode", true),
    MODES_SELECT_MODE_SEND3(CommandCategory.MODES, "Modes: Select Send 3 Mode", true),
    MODES_SELECT_MODE_SEND4(CommandCategory.MODES, "Modes: Select Send 4 Mode", true),
    MODES_SELECT_MODE_SEND5(CommandCategory.MODES, "Modes: Select Send 5 Mode", true),
    MODES_SELECT_MODE_SEND6(CommandCategory.MODES, "Modes: Select Send 6 Mode", true),
    MODES_SELECT_MODE_SEND7(CommandCategory.MODES, "Modes: Select Send 7 Mode", true),
    MODES_SELECT_MODE_SEND8(CommandCategory.MODES, "Modes: Select Send 8 Mode", true),
    MODES_SELECT_MODE_DEVICE(CommandCategory.MODES, "Modes: Select Device Mode", true),
    MODES_SELECT_MODE_NEXT(CommandCategory.MODES, "Modes: Select Next Mode", true),
    MODES_SELECT_MODE_PREV(CommandCategory.MODES, "Modes: Select Previous Mode", true),
    MODES_BROWSE_PRESETS(CommandCategory.MODES, "Modes: Start Browser: Browse Presets", true),

    MIDI_CC_0(CommandCategory.MIDI_CC, "MIDI CC: 0   Bank Select", false),
    MIDI_CC_1(CommandCategory.MIDI_CC, "MIDI CC: 1   Modulation", false),
    MIDI_CC_2(CommandCategory.MIDI_CC, "MIDI CC: 2   Breath Controller", false),
    MIDI_CC_3(CommandCategory.MIDI_CC, "MIDI CC: 3   -", false),
    MIDI_CC_4(CommandCategory.MIDI_CC, "MIDI CC: 4   Foot Controller", false),
    MIDI_CC_5(CommandCategory.MIDI_CC, "MIDI CC: 5   Portamento Time", false),
    MIDI_CC_6(CommandCategory.MIDI_CC, "MIDI CC: 6   Data Entry MSB", false),
    MIDI_CC_7(CommandCategory.MIDI_CC, "MIDI CC: 7   Volume", false),
    MIDI_CC_8(CommandCategory.MIDI_CC, "MIDI CC: 8   Balance", false),
    MIDI_CC_9(CommandCategory.MIDI_CC, "MIDI CC: 9   -", false),
    MIDI_CC_10(CommandCategory.MIDI_CC, "MIDI CC: 10  Pan", false),
    MIDI_CC_11(CommandCategory.MIDI_CC, "MIDI CC: 11  Expression", false),
    MIDI_CC_12(CommandCategory.MIDI_CC, "MIDI CC: 12  Effect Controller 1", false),
    MIDI_CC_13(CommandCategory.MIDI_CC, "MIDI CC: 13  Effect Controller 2", false),
    MIDI_CC_14(CommandCategory.MIDI_CC, "MIDI CC: 14  -", false),
    MIDI_CC_15(CommandCategory.MIDI_CC, "MIDI CC: 15  -", false),
    MIDI_CC_16(CommandCategory.MIDI_CC, "MIDI CC: 16  -", false),
    MIDI_CC_17(CommandCategory.MIDI_CC, "MIDI CC: 17  -", false),
    MIDI_CC_18(CommandCategory.MIDI_CC, "MIDI CC: 18  -", false),
    MIDI_CC_19(CommandCategory.MIDI_CC, "MIDI CC: 19  -", false),
    MIDI_CC_20(CommandCategory.MIDI_CC, "MIDI CC: 20  -", false),
    MIDI_CC_21(CommandCategory.MIDI_CC, "MIDI CC: 21  -", false),
    MIDI_CC_22(CommandCategory.MIDI_CC, "MIDI CC: 22  -", false),
    MIDI_CC_23(CommandCategory.MIDI_CC, "MIDI CC: 23  -", false),
    MIDI_CC_24(CommandCategory.MIDI_CC, "MIDI CC: 24  -", false),
    MIDI_CC_25(CommandCategory.MIDI_CC, "MIDI CC: 25  -", false),
    MIDI_CC_26(CommandCategory.MIDI_CC, "MIDI CC: 26  -", false),
    MIDI_CC_27(CommandCategory.MIDI_CC, "MIDI CC: 27  -", false),
    MIDI_CC_28(CommandCategory.MIDI_CC, "MIDI CC: 28  -", false),
    MIDI_CC_29(CommandCategory.MIDI_CC, "MIDI CC: 29  -", false),
    MIDI_CC_30(CommandCategory.MIDI_CC, "MIDI CC: 30  -", false),
    MIDI_CC_31(CommandCategory.MIDI_CC, "MIDI CC: 31  -", false),
    MIDI_CC_32(CommandCategory.MIDI_CC, "MIDI CC: 32  -", false),
    MIDI_CC_33(CommandCategory.MIDI_CC, "MIDI CC: 33  -", false),
    MIDI_CC_34(CommandCategory.MIDI_CC, "MIDI CC: 34  -", false),
    MIDI_CC_35(CommandCategory.MIDI_CC, "MIDI CC: 35  -", false),
    MIDI_CC_36(CommandCategory.MIDI_CC, "MIDI CC: 36  -", false),
    MIDI_CC_37(CommandCategory.MIDI_CC, "MIDI CC: 37  -", false),
    MIDI_CC_38(CommandCategory.MIDI_CC, "MIDI CC: 38  -", false),
    MIDI_CC_39(CommandCategory.MIDI_CC, "MIDI CC: 39  -", false),
    MIDI_CC_40(CommandCategory.MIDI_CC, "MIDI CC: 40  -", false),
    MIDI_CC_41(CommandCategory.MIDI_CC, "MIDI CC: 41  -", false),
    MIDI_CC_42(CommandCategory.MIDI_CC, "MIDI CC: 42  -", false),
    MIDI_CC_43(CommandCategory.MIDI_CC, "MIDI CC: 43  -", false),
    MIDI_CC_44(CommandCategory.MIDI_CC, "MIDI CC: 44  -", false),
    MIDI_CC_45(CommandCategory.MIDI_CC, "MIDI CC: 45  -", false),
    MIDI_CC_46(CommandCategory.MIDI_CC, "MIDI CC: 46  -", false),
    MIDI_CC_47(CommandCategory.MIDI_CC, "MIDI CC: 47  -", false),
    MIDI_CC_48(CommandCategory.MIDI_CC, "MIDI CC: 48  -", false),
    MIDI_CC_49(CommandCategory.MIDI_CC, "MIDI CC: 49  -", false),
    MIDI_CC_50(CommandCategory.MIDI_CC, "MIDI CC: 50  -", false),
    MIDI_CC_51(CommandCategory.MIDI_CC, "MIDI CC: 51  -", false),
    MIDI_CC_52(CommandCategory.MIDI_CC, "MIDI CC: 52  -", false),
    MIDI_CC_53(CommandCategory.MIDI_CC, "MIDI CC: 53  -", false),
    MIDI_CC_54(CommandCategory.MIDI_CC, "MIDI CC: 54  -", false),
    MIDI_CC_55(CommandCategory.MIDI_CC, "MIDI CC: 55  -", false),
    MIDI_CC_56(CommandCategory.MIDI_CC, "MIDI CC: 56  -", false),
    MIDI_CC_57(CommandCategory.MIDI_CC, "MIDI CC: 57  -", false),
    MIDI_CC_58(CommandCategory.MIDI_CC, "MIDI CC: 58  -", false),
    MIDI_CC_59(CommandCategory.MIDI_CC, "MIDI CC: 59  -", false),
    MIDI_CC_60(CommandCategory.MIDI_CC, "MIDI CC: 60  -", false),
    MIDI_CC_61(CommandCategory.MIDI_CC, "MIDI CC: 61  -", false),
    MIDI_CC_62(CommandCategory.MIDI_CC, "MIDI CC: 62  -", false),
    MIDI_CC_63(CommandCategory.MIDI_CC, "MIDI CC: 63  -", false),
    MIDI_CC_64(CommandCategory.MIDI_CC, "MIDI CC: 64  Damper Pedal", false),
    MIDI_CC_65(CommandCategory.MIDI_CC, "MIDI CC: 65  Portamento On/Off Switch", false),
    MIDI_CC_66(CommandCategory.MIDI_CC, "MIDI CC: 66  Sostenuto On/Off Switch", false),
    MIDI_CC_67(CommandCategory.MIDI_CC, "MIDI CC: 67  Soft Pedal On/Off Switch", false),
    MIDI_CC_68(CommandCategory.MIDI_CC, "MIDI CC: 68  Legato Footswitch", false),
    MIDI_CC_69(CommandCategory.MIDI_CC, "MIDI CC: 69  Hold 2", false),
    MIDI_CC_70(CommandCategory.MIDI_CC, "MIDI CC: 70  Sound Controller 1", false),
    MIDI_CC_71(CommandCategory.MIDI_CC, "MIDI CC: 71  Sound Controller 2", false),
    MIDI_CC_72(CommandCategory.MIDI_CC, "MIDI CC: 72  Sound Controller 3", false),
    MIDI_CC_73(CommandCategory.MIDI_CC, "MIDI CC: 73  Sound Controller 4", false),
    MIDI_CC_74(CommandCategory.MIDI_CC, "MIDI CC: 74  Sound Controller 5", false),
    MIDI_CC_75(CommandCategory.MIDI_CC, "MIDI CC: 75  Sound Controller 6", false),
    MIDI_CC_76(CommandCategory.MIDI_CC, "MIDI CC: 76  Sound Controller 7", false),
    MIDI_CC_77(CommandCategory.MIDI_CC, "MIDI CC: 77  Sound Controller 8", false),
    MIDI_CC_78(CommandCategory.MIDI_CC, "MIDI CC: 78  Sound Controller 9", false),
    MIDI_CC_79(CommandCategory.MIDI_CC, "MIDI CC: 79  Sound Controller 10", false),
    MIDI_CC_80(CommandCategory.MIDI_CC, "MIDI CC: 80  General Purpose", false),
    MIDI_CC_81(CommandCategory.MIDI_CC, "MIDI CC: 81  General Purpose", false),
    MIDI_CC_82(CommandCategory.MIDI_CC, "MIDI CC: 82  General Purpose", false),
    MIDI_CC_83(CommandCategory.MIDI_CC, "MIDI CC: 83  General Purpose", false),
    MIDI_CC_84(CommandCategory.MIDI_CC, "MIDI CC: 84  Portamento", false),
    MIDI_CC_85(CommandCategory.MIDI_CC, "MIDI CC: 85  -", false),
    MIDI_CC_86(CommandCategory.MIDI_CC, "MIDI CC: 86  -", false),
    MIDI_CC_87(CommandCategory.MIDI_CC, "MIDI CC: 87  -", false),
    MIDI_CC_88(CommandCategory.MIDI_CC, "MIDI CC: 88  -", false),
    MIDI_CC_89(CommandCategory.MIDI_CC, "MIDI CC: 89  -", false),
    MIDI_CC_90(CommandCategory.MIDI_CC, "MIDI CC: 90  -", false),
    MIDI_CC_91(CommandCategory.MIDI_CC, "MIDI CC: 91  Effect 1 Depth", false),
    MIDI_CC_92(CommandCategory.MIDI_CC, "MIDI CC: 92  Effect 2 Depth", false),
    MIDI_CC_93(CommandCategory.MIDI_CC, "MIDI CC: 93  Effect 3 Depth", false),
    MIDI_CC_94(CommandCategory.MIDI_CC, "MIDI CC: 94  Effect 4 Depth", false),
    MIDI_CC_95(CommandCategory.MIDI_CC, "MIDI CC: 95  Effect 5 Depth", false),
    MIDI_CC_96(CommandCategory.MIDI_CC, "MIDI CC: 96  (+1) Data Increment", false),
    MIDI_CC_97(CommandCategory.MIDI_CC, "MIDI CC: 97  (-1) Data Decrement", false),
    MIDI_CC_98(CommandCategory.MIDI_CC, "MIDI CC: 98  NRPN LSB", false),
    MIDI_CC_99(CommandCategory.MIDI_CC, "MIDI CC: 99  NRPN MSB", false),
    MIDI_CC_100(CommandCategory.MIDI_CC, "MIDI CC: 100 RPN LSB", false),
    MIDI_CC_101(CommandCategory.MIDI_CC, "MIDI CC: 101 RPN MSB", false),
    MIDI_CC_102(CommandCategory.MIDI_CC, "MIDI CC: 102 -", false),
    MIDI_CC_103(CommandCategory.MIDI_CC, "MIDI CC: 103 -", false),
    MIDI_CC_104(CommandCategory.MIDI_CC, "MIDI CC: 104 -", false),
    MIDI_CC_105(CommandCategory.MIDI_CC, "MIDI CC: 105 -", false),
    MIDI_CC_106(CommandCategory.MIDI_CC, "MIDI CC: 106 -", false),
    MIDI_CC_107(CommandCategory.MIDI_CC, "MIDI CC: 107 -", false),
    MIDI_CC_108(CommandCategory.MIDI_CC, "MIDI CC: 108 -", false),
    MIDI_CC_109(CommandCategory.MIDI_CC, "MIDI CC: 109 -", false),
    MIDI_CC_110(CommandCategory.MIDI_CC, "MIDI CC: 110 -", false),
    MIDI_CC_111(CommandCategory.MIDI_CC, "MIDI CC: 111 -", false),
    MIDI_CC_112(CommandCategory.MIDI_CC, "MIDI CC: 112 -", false),
    MIDI_CC_113(CommandCategory.MIDI_CC, "MIDI CC: 113 -", false),
    MIDI_CC_114(CommandCategory.MIDI_CC, "MIDI CC: 114 -", false),
    MIDI_CC_115(CommandCategory.MIDI_CC, "MIDI CC: 115 -", false),
    MIDI_CC_116(CommandCategory.MIDI_CC, "MIDI CC: 116 -", false),
    MIDI_CC_117(CommandCategory.MIDI_CC, "MIDI CC: 117 -", false),
    MIDI_CC_118(CommandCategory.MIDI_CC, "MIDI CC: 118 -", false),
    MIDI_CC_119(CommandCategory.MIDI_CC, "MIDI CC: 119 -", false),
    MIDI_CC_120(CommandCategory.MIDI_CC, "MIDI CC: 120 All Sound Off", false),
    MIDI_CC_121(CommandCategory.MIDI_CC, "MIDI CC: 121 Reset All Controllers", false),
    MIDI_CC_122(CommandCategory.MIDI_CC, "MIDI CC: 122 Local On/Off Switch", false),
    MIDI_CC_123(CommandCategory.MIDI_CC, "MIDI CC: 123 All Notes Off", false),
    MIDI_CC_124(CommandCategory.MIDI_CC, "MIDI CC: 124 Omni Mode Off", false),
    MIDI_CC_125(CommandCategory.MIDI_CC, "MIDI CC: 125 Omni Mode On", false),
    MIDI_CC_126(CommandCategory.MIDI_CC, "MIDI CC: 126 Mono Mode", false),
    MIDI_CC_127(CommandCategory.MIDI_CC, "MIDI CC: 127 Poly Mode", false),

    NOTE_INPUT_REPEAT_ACTIVE(CommandCategory.NOTE_INPUT, "Note Input: Toggle Note Repeat Active", true),
    NOTE_INPUT_REPEAT_PERIOD(CommandCategory.NOTE_INPUT, "Note Input: Set Note Repeat Period", false),
    NOTE_INPUT_REPEAT_LENGTH(CommandCategory.NOTE_INPUT, "Note Input: Set Note Repeat Length", false),
    NOTE_INPUT_REPEAT_MODE(CommandCategory.NOTE_INPUT, "Note Input: Set Note Repeat Mode", false),
    NOTE_INPUT_REPEAT_OCTAVE(CommandCategory.NOTE_INPUT, "Note Input: Set Note Repeat Octave", false),
    NOTE_INPUT_TRANSPOSE_OCTAVE_UP(CommandCategory.NOTE_INPUT, "Note Input: Transpose Octave Up", false),
    NOTE_INPUT_TRANSPOSE_OCTAVE_DOWN(CommandCategory.NOTE_INPUT, "Note Input: Transpose Octave Down", false),

    USER_SET_PARAMETER_1(CommandCategory.USER, "User: Set Parameter 1", false),
    USER_SET_PARAMETER_2(CommandCategory.USER, "User: Set Parameter 2", false),
    USER_SET_PARAMETER_3(CommandCategory.USER, "User: Set Parameter 3", false),
    USER_SET_PARAMETER_4(CommandCategory.USER, "User: Set Parameter 4", false),
    USER_SET_PARAMETER_5(CommandCategory.USER, "User: Set Parameter 5", false),
    USER_SET_PARAMETER_6(CommandCategory.USER, "User: Set Parameter 6", false),
    USER_SET_PARAMETER_7(CommandCategory.USER, "User: Set Parameter 7", false),
    USER_SET_PARAMETER_8(CommandCategory.USER, "User: Set Parameter 8", false),
    USER_RESET_PARAMETER_1(CommandCategory.USER, "User: Reset Parameter 1", false),
    USER_RESET_PARAMETER_2(CommandCategory.USER, "User: Reset Parameter 2", false),
    USER_RESET_PARAMETER_3(CommandCategory.USER, "User: Reset Parameter 3", false),
    USER_RESET_PARAMETER_4(CommandCategory.USER, "User: Reset Parameter 4", false),
    USER_RESET_PARAMETER_5(CommandCategory.USER, "User: Reset Parameter 5", false),
    USER_RESET_PARAMETER_6(CommandCategory.USER, "User: Reset Parameter 6", false),
    USER_RESET_PARAMETER_7(CommandCategory.USER, "User: Reset Parameter 7", false),
    USER_RESET_PARAMETER_8(CommandCategory.USER, "User: Reset Parameter 8", false),
    USER_TOGGLE_PARAMETER_1(CommandCategory.USER, "User: Toggle Parameter 1", true),
    USER_TOGGLE_PARAMETER_2(CommandCategory.USER, "User: Toggle Parameter 2", true),
    USER_TOGGLE_PARAMETER_3(CommandCategory.USER, "User: Toggle Parameter 3", true),
    USER_TOGGLE_PARAMETER_4(CommandCategory.USER, "User: Toggle Parameter 4", true),
    USER_TOGGLE_PARAMETER_5(CommandCategory.USER, "User: Toggle Parameter 5", true),
    USER_TOGGLE_PARAMETER_6(CommandCategory.USER, "User: Toggle Parameter 6", true),
    USER_TOGGLE_PARAMETER_7(CommandCategory.USER, "User: Toggle Parameter 7", true),
    USER_TOGGLE_PARAMETER_8(CommandCategory.USER, "User: Toggle Parameter 8", true),
    USER_SELECT_PREVIOUS_PAGE(CommandCategory.USER, "User: Select Previous Page", true),
    USER_SELECT_NEXT_PAGE(CommandCategory.USER, "User: Select Next Page", true),

    ACTION_1(CommandCategory.ACTION, "Action: Execute Action 1", true),
    ACTION_2(CommandCategory.ACTION, "Action: Execute Action 2", true),
    ACTION_3(CommandCategory.ACTION, "Action: Execute Action 3", true),
    ACTION_4(CommandCategory.ACTION, "Action: Execute Action 4", true),
    ACTION_5(CommandCategory.ACTION, "Action: Execute Action 5", true),
    ACTION_6(CommandCategory.ACTION, "Action: Execute Action 6", true),
    ACTION_7(CommandCategory.ACTION, "Action: Execute Action 7", true),
    ACTION_8(CommandCategory.ACTION, "Action: Execute Action 8", true);


    private static final String []                 NAMES;
    private static final Map<String, FlexiCommand> NAME_COMMAND_MAP;

    static
    {
        final FlexiCommand [] values = FlexiCommand.values ();
        NAMES = new String [values.length];
        NAME_COMMAND_MAP = new HashMap<> (values.length);
        for (int i = 0; i < values.length; i++)
        {
            NAMES[i] = values[i].getName ();
            NAME_COMMAND_MAP.put (NAMES[i], values[i]);
        }
    }

    private final CommandCategory category;
    private final String          name;
    private final boolean         isTrigger;


    /**
     * Constructor.
     *
     * @param name The name of the command
     * @param isTrigger True if it is a trigger command (push button)
     */
    private FlexiCommand (final CommandCategory category, final String name, final boolean isTrigger)
    {
        this.category = category;
        this.name = name;
        this.isTrigger = isTrigger;
    }


    /**
     * Get the category of the command.
     *
     * @return The category
     */
    public CommandCategory getCategory ()
    {
        return this.category;
    }


    /**
     * Get the name of the command.
     *
     * @return The name
     */
    public String getName ()
    {
        return this.name;
    }


    /**
     * Get if the command is a trigger command.
     *
     * @return True if can be triggered
     */
    public boolean isTrigger ()
    {
        return this.isTrigger;
    }


    /**
     * Get the names of all commands.
     *
     * @return The names
     */
    public static String [] getNames ()
    {
        return NAMES;
    }


    /**
     * Lookup the command by its name.
     *
     * @param name The name
     * @return The command or if not found the OFF command
     */
    public static FlexiCommand lookupByName (final String name)
    {
        return NAME_COMMAND_MAP.getOrDefault (name, FlexiCommand.OFF);
    }
}
