package de.mossgrabers.controller.generic.controller;

@SuppressWarnings("javadoc")
public enum FlexiCommand
{
    OFF("Off", false),
    GLOBAL_UNDO("Global: Undo", true),
    GLOBAL_REDO("Global: Redo", true),
    GLOBAL_PREVIOUS_PROJECT("Global: Previous Project", true),
    GLOBAL_NEXT_PROJECT("Global: Next Project", true),
    GLOBAL_TOGGLE_AUDIO_ENGINE("Global: Toggle Audio Engine", true),
    TRANSPORT_PLAY("Transport: Play", true),
    TRANSPORT_STOP("Transport: Stop", true),
    TRANSPORT_RESTART("Transport: Restart", true),
    TRANSPORT_TOGGLE_REPEAT("Transport: Toggle Repeat", true),
    TRANSPORT_TOGGLE_METRONOME("Transport: Toggle Metronome", true),
    TRANSPORT_SET_METRONOME_VOLUME("Transport: Set Metronome Volume", false),
    TRANSPORT_TOGGLE_METRONOME_IN_PREROLL("Transport: Toggle Metronome in Pre-roll", true),
    TRANSPORT_TOGGLE_PUNCH_IN("Transport: Toggle Punch In", true),
    TRANSPORT_TOGGLE_PUNCH_OUT("Transport: Toggle Punch Out", true),
    TRANSPORT_TOGGLE_RECORD("Transport: Toggle Record", true),
    TRANSPORT_TOGGLE_ARRANGER_OVERDUB("Transport: Toggle Arranger Overdub", true),
    TRANSPORT_TOGGLE_CLIP_OVERDUB("Transport: Toggle Clip Overdub", true),
    TRANSPORT_SET_CROSSFADER("Transport: Set Crossfader", false),
    TRANSPORT_TOGGLE_ARRANGER_AUTOMATION_WRITE("Transport: Toggle Arranger Automation Write", true),
    TRANSPORT_TOGGLE_CLIP_AUTOMATION_WRITE("Transport: Toggle Clip Automation Write", true),
    TRANSPORT_SET_WRITE_MODE_LATCH("Transport: Set Write Mode: Latch", true),
    TRANSPORT_SET_WRITE_MODE_TOUCH("Transport: Set Write Mode: Touch", true),
    TRANSPORT_SET_WRITE_MODE_WRITE("Transport: Set Write Mode: Write", true),
    TRANSPORT_SET_TEMPO("Transport: Set Tempo", false),
    TRANSPORT_TAP_TEMPO("Transport: Tap Tempo", true),
    TRANSPORT_MOVE_PLAY_CURSOR("Transport: Move Play Cursor", false),
    LAYOUT_SET_ARRANGE_LAYOUT("Layout: Set Arrange Layout", true),
    LAYOUT_SET_MIX_LAYOUT("Layout: Set Mix Layout", true),
    LAYOUT_SET_EDIT_LAYOUT("Layout: Set Edit Layout", true),
    LAYOUT_TOGGLE_NOTE_EDITOR("Layout: Toggle Note Editor", true),
    LAYOUT_TOGGLE_AUTOMATION_EDITOR("Layout: Toggle Automation Editor", true),
    LAYOUT_TOGGLE_DEVICES_PANEL("Layout: Toggle Devices Panel", true),
    LAYOUT_TOGGLE_MIXER_PANEL("Layout: Toggle Mixer Panel", true),
    LAYOUT_TOGGLE_FULLSCREEN("Layout: Toggle Fullscreen", true),
    LAYOUT_TOGGLE_ARRANGER_CUE_MARKERS("Layout: Toggle Arranger Cue Markers", true),
    LAYOUT_TOGGLE_ARRANGER_PLAYBACK_FOLLOW("Layout: Toggle Arranger Playback Follow", true),
    LAYOUT_TOGGLE_ARRANGER_TRACK_ROW_HEIGHT("Layout: Toggle Arranger Track Row Height", true),
    LAYOUT_TOGGLE_ARRANGER_CLIP_LAUNCHER_SECTION("Layout: Toggle Arranger Clip Launcher Section", true),
    LAYOUT_TOGGLE_ARRANGER_TIME_LINE("Layout: Toggle Arranger Time Line", true),
    LAYOUT_TOGGLE_ARRANGER_IO_SECTION("Layout: Toggle Arranger IO Section", true),
    LAYOUT_TOGGLE_ARRANGER_EFFECT_TRACKS("Layout: Toggle Arranger Effect Tracks", true),
    LAYOUT_TOGGLE_MIXER_CLIP_LAUNCHER_SECTION("Layout: Toggle Mixer Clip Launcher Section", true),
    LAYOUT_TOGGLE_MIXER_CROSS_FADE_SECTION("Layout: Toggle Mixer Cross Fade Section", true),
    LAYOUT_TOGGLE_MIXER_DEVICE_SECTION("Layout: Toggle Mixer Device Section", true),
    LAYOUT_TOGGLE_MIXER_SENDSSECTION("Layout: Toggle Mixer sendsSection", true),
    LAYOUT_TOGGLE_MIXER_IO_SECTION("Layout: Toggle Mixer IO Section", true),
    LAYOUT_TOGGLE_MIXER_METER_SECTION("Layout: Toggle Mixer Meter Section", true),
    TRACK_ADD_AUDIO_TRACK("Track: Add Audio Track", true),
    TRACK_ADD_EFFECT_TRACK("Track: Add Effect Track", true),
    TRACK_ADD_INSTRUMENT_TRACK("Track: Add Instrument Track", true),
    TRACK_SELECT_PREVIOUS_BANK_PAGE("Track: Select Previous Bank Page", true),
    TRACK_SELECT_NEXT_BANK_PAGE("Track: Select Next Bank Page", true),
    TRACK_SELECT_PREVIOUS_TRACK("Track: Select Previous Track", true),
    TRACK_SELECT_NEXT_TRACK("Track: Select Next Track", true),
    TRACK_SCROLL_TRACKS("Track: Scroll Tracks", false),
    TRACK_1_SELECT("Track 1: Select", true),
    TRACK_2_SELECT("Track 2: Select", true),
    TRACK_3_SELECT("Track 3: Select", true),
    TRACK_4_SELECT("Track 4: Select", true),
    TRACK_5_SELECT("Track 5: Select", true),
    TRACK_6_SELECT("Track 6: Select", true),
    TRACK_7_SELECT("Track 7: Select", true),
    TRACK_8_SELECT("Track 8: Select", true),
    TRACK_1_TOGGLE_ACTIVE("Track 1: Toggle Active", true),
    TRACK_2_TOGGLE_ACTIVE("Track 2: Toggle Active", true),
    TRACK_3_TOGGLE_ACTIVE("Track 3: Toggle Active", true),
    TRACK_4_TOGGLE_ACTIVE("Track 4: Toggle Active", true),
    TRACK_5_TOGGLE_ACTIVE("Track 5: Toggle Active", true),
    TRACK_6_TOGGLE_ACTIVE("Track 6: Toggle Active", true),
    TRACK_7_TOGGLE_ACTIVE("Track 7: Toggle Active", true),
    TRACK_8_TOGGLE_ACTIVE("Track 8: Toggle Active", true),
    TRACK_SELECTED_TOGGLE_ACTIVE("Track Selected: Toggle Active", true),
    TRACK_1_SET_VOLUME("Track 1: Set Volume", false),
    TRACK_2_SET_VOLUME("Track 2: Set Volume", false),
    TRACK_3_SET_VOLUME("Track 3: Set Volume", false),
    TRACK_4_SET_VOLUME("Track 4: Set Volume", false),
    TRACK_5_SET_VOLUME("Track 5: Set Volume", false),
    TRACK_6_SET_VOLUME("Track 6: Set Volume", false),
    TRACK_7_SET_VOLUME("Track 7: Set Volume", false),
    TRACK_8_SET_VOLUME("Track 8: Set Volume", false),
    TRACK_SELECTED_SET_VOLUME_TRACK("Track Selected: Set Volume Track", false),
    TRACK_1_SET_PANORAMA("Track 1: Set Panorama", false),
    TRACK_2_SET_PANORAMA("Track 2: Set Panorama", false),
    TRACK_3_SET_PANORAMA("Track 3: Set Panorama", false),
    TRACK_4_SET_PANORAMA("Track 4: Set Panorama", false),
    TRACK_5_SET_PANORAMA("Track 5: Set Panorama", false),
    TRACK_6_SET_PANORAMA("Track 6: Set Panorama", false),
    TRACK_7_SET_PANORAMA("Track 7: Set Panorama", false),
    TRACK_8_SET_PANORAMA("Track 8: Set Panorama", false),
    TRACK_SELECTED_SET_PANORAMA("Track Selected: Set Panorama", false),
    TRACK_1_TOGGLE_MUTE("Track 1: Toggle Mute", true),
    TRACK_2_TOGGLE_MUTE("Track 2: Toggle Mute", true),
    TRACK_3_TOGGLE_MUTE("Track 3: Toggle Mute", true),
    TRACK_4_TOGGLE_MUTE("Track 4: Toggle Mute", true),
    TRACK_5_TOGGLE_MUTE("Track 5: Toggle Mute", true),
    TRACK_6_TOGGLE_MUTE("Track 6: Toggle Mute", true),
    TRACK_7_TOGGLE_MUTE("Track 7: Toggle Mute", true),
    TRACK_8_TOGGLE_MUTE("Track 8: Toggle Mute", true),
    TRACK_SELECTED_TOGGLE_MUTE("Track Selected: Toggle Mute", true),
    TRACK_1_TOGGLE_SOLO("Track 1: Toggle Solo", true),
    TRACK_2_TOGGLE_SOLO("Track 2: Toggle Solo", true),
    TRACK_3_TOGGLE_SOLO("Track 3: Toggle Solo", true),
    TRACK_4_TOGGLE_SOLO("Track 4: Toggle Solo", true),
    TRACK_5_TOGGLE_SOLO("Track 5: Toggle Solo", true),
    TRACK_6_TOGGLE_SOLO("Track 6: Toggle Solo", true),
    TRACK_7_TOGGLE_SOLO("Track 7: Toggle Solo", true),
    TRACK_8_TOGGLE_SOLO("Track 8: Toggle Solo", true),
    TRACK_SELECTED_TOGGLE_SOLO("Track Selected: Toggle Solo", true),
    TRACK_1_TOGGLE_ARM("Track 1: Toggle Arm", true),
    TRACK_2_TOGGLE_ARM("Track 2: Toggle Arm", true),
    TRACK_3_TOGGLE_ARM("Track 3: Toggle Arm", true),
    TRACK_4_TOGGLE_ARM("Track 4: Toggle Arm", true),
    TRACK_5_TOGGLE_ARM("Track 5: Toggle Arm", true),
    TRACK_6_TOGGLE_ARM("Track 6: Toggle Arm", true),
    TRACK_7_TOGGLE_ARM("Track 7: Toggle Arm", true),
    TRACK_8_TOGGLE_ARM("Track 8: Toggle Arm", true),
    TRACK_SELECTED_TOGGLE_ARM("Track Selected: Toggle Arm", true),
    TRACK_1_TOGGLE_MONITOR("Track 1: Toggle Monitor", true),
    TRACK_2_TOGGLE_MONITOR("Track 2: Toggle Monitor", true),
    TRACK_3_TOGGLE_MONITOR("Track 3: Toggle Monitor", true),
    TRACK_4_TOGGLE_MONITOR("Track 4: Toggle Monitor", true),
    TRACK_5_TOGGLE_MONITOR("Track 5: Toggle Monitor", true),
    TRACK_6_TOGGLE_MONITOR("Track 6: Toggle Monitor", true),
    TRACK_7_TOGGLE_MONITOR("Track 7: Toggle Monitor", true),
    TRACK_8_TOGGLE_MONITOR("Track 8: Toggle Monitor", true),
    TRACK_SELECTED_TOGGLE_MONITOR("Track Selected: Toggle Monitor", true),
    TRACK_1_TOGGLE_AUTO_MONITOR("Track 1: Toggle Auto Monitor", true),
    TRACK_2_TOGGLE_AUTO_MONITOR("Track 2: Toggle Auto Monitor", true),
    TRACK_3_TOGGLE_AUTO_MONITOR("Track 3: Toggle Auto Monitor", true),
    TRACK_4_TOGGLE_AUTO_MONITOR("Track 4: Toggle Auto Monitor", true),
    TRACK_5_TOGGLE_AUTO_MONITOR("Track 5: Toggle Auto Monitor", true),
    TRACK_6_TOGGLE_AUTO_MONITOR("Track 6: Toggle Auto Monitor", true),
    TRACK_7_TOGGLE_AUTO_MONITOR("Track 7: Toggle Auto Monitor", true),
    TRACK_8_TOGGLE_AUTO_MONITOR("Track 8: Toggle Auto Monitor", true),
    TRACK_SELECTED_TOGGLE_AUTO_MONITOR("Track Selected: Toggle Auto Monitor", true),
    TRACK_1_SET_SEND_1("Track 1: Set Send 1", false),
    TRACK_2_SET_SEND_1("Track 2: Set Send 1", false),
    TRACK_3_SET_SEND_1("Track 3: Set Send 1", false),
    TRACK_4_SET_SEND_1("Track 4: Set Send 1", false),
    TRACK_5_SET_SEND_1("Track 5: Set Send 1", false),
    TRACK_6_SET_SEND_1("Track 6: Set Send 1", false),
    TRACK_7_SET_SEND_1("Track 7: Set Send 1", false),
    TRACK_8_SET_SEND_1("Track 8: Set Send 1", false),
    TRACK_1_SET_SEND_2("Track 1: Set Send 2", false),
    TRACK_2_SET_SEND_2("Track 2: Set Send 2", false),
    TRACK_3_SET_SEND_2("Track 3: Set Send 2", false),
    TRACK_4_SET_SEND_2("Track 4: Set Send 2", false),
    TRACK_5_SET_SEND_2("Track 5: Set Send 2", false),
    TRACK_6_SET_SEND_2("Track 6: Set Send 2", false),
    TRACK_7_SET_SEND_2("Track 7: Set Send 2", false),
    TRACK_8_SET_SEND_2("Track 8: Set Send 2", false),
    TRACK_1_SET_SEND_3("Track 1: Set Send 3", false),
    TRACK_2_SET_SEND_3("Track 2: Set Send 3", false),
    TRACK_3_SET_SEND_3("Track 3: Set Send 3", false),
    TRACK_4_SET_SEND_3("Track 4: Set Send 3", false),
    TRACK_5_SET_SEND_3("Track 5: Set Send 3", false),
    TRACK_6_SET_SEND_3("Track 6: Set Send 3", false),
    TRACK_7_SET_SEND_3("Track 7: Set Send 3", false),
    TRACK_8_SET_SEND_3("Track 8: Set Send 3", false),
    TRACK_1_SET_SEND_4("Track 1: Set Send 4", false),
    TRACK_2_SET_SEND_4("Track 2: Set Send 4", false),
    TRACK_3_SET_SEND_4("Track 3: Set Send 4", false),
    TRACK_4_SET_SEND_4("Track 4: Set Send 4", false),
    TRACK_5_SET_SEND_4("Track 5: Set Send 4", false),
    TRACK_6_SET_SEND_4("Track 6: Set Send 4", false),
    TRACK_7_SET_SEND_4("Track 7: Set Send 4", false),
    TRACK_8_SET_SEND_4("Track 8: Set Send 4", false),
    TRACK_1_SET_SEND_5("Track 1: Set Send 5", false),
    TRACK_2_SET_SEND_5("Track 2: Set Send 5", false),
    TRACK_3_SET_SEND_5("Track 3: Set Send 5", false),
    TRACK_4_SET_SEND_5("Track 4: Set Send 5", false),
    TRACK_5_SET_SEND_5("Track 5: Set Send 5", false),
    TRACK_6_SET_SEND_5("Track 6: Set Send 5", false),
    TRACK_7_SET_SEND_5("Track 7: Set Send 5", false),
    TRACK_8_SET_SEND_5("Track 8: Set Send 5", false),
    TRACK_1_SET_SEND_6("Track 1: Set Send 6", false),
    TRACK_2_SET_SEND_6("Track 2: Set Send 6", false),
    TRACK_3_SET_SEND_6("Track 3: Set Send 6", false),
    TRACK_4_SET_SEND_6("Track 4: Set Send 6", false),
    TRACK_5_SET_SEND_6("Track 5: Set Send 6", false),
    TRACK_6_SET_SEND_6("Track 6: Set Send 6", false),
    TRACK_7_SET_SEND_6("Track 7: Set Send 6", false),
    TRACK_8_SET_SEND_6("Track 8: Set Send 6", false),
    TRACK_1_SET_SEND_7("Track 1: Set Send 7", false),
    TRACK_2_SET_SEND_7("Track 2: Set Send 7", false),
    TRACK_3_SET_SEND_7("Track 3: Set Send 7", false),
    TRACK_4_SET_SEND_7("Track 4: Set Send 7", false),
    TRACK_5_SET_SEND_7("Track 5: Set Send 7", false),
    TRACK_6_SET_SEND_7("Track 6: Set Send 7", false),
    TRACK_7_SET_SEND_7("Track 7: Set Send 7", false),
    TRACK_8_SET_SEND_7("Track 8: Set Send 7", false),
    TRACK_1_SET_SEND_8("Track 1: Set Send 8", false),
    TRACK_2_SET_SEND_8("Track 2: Set Send 8", false),
    TRACK_3_SET_SEND_8("Track 3: Set Send 8", false),
    TRACK_4_SET_SEND_8("Track 4: Set Send 8", false),
    TRACK_5_SET_SEND_8("Track 5: Set Send 8", false),
    TRACK_6_SET_SEND_8("Track 6: Set Send 8", false),
    TRACK_7_SET_SEND_8("Track 7: Set Send 8", false),
    TRACK_8_SET_SEND_8("Track 8: Set Send 8", false),
    TRACK_SELECTED_SET_SEND_1("Track Selected: Set Send 1", false),
    TRACK_SELECTED_SET_SEND_2("Track Selected: Set Send 2", false),
    TRACK_SELECTED_SET_SEND_3("Track Selected: Set Send 3", false),
    TRACK_SELECTED_SET_SEND_4("Track Selected: Set Send 4", false),
    TRACK_SELECTED_SET_SEND_5("Track Selected: Set Send 5", false),
    TRACK_SELECTED_SET_SEND_6("Track Selected: Set Send 6", false),
    TRACK_SELECTED_SET_SEND_7("Track Selected: Set Send 7", false),
    TRACK_SELECTED_SET_SEND_8("Track Selected: Set Send 8", false),
    MASTER_SET_VOLUME("Master: Set Volume", false),
    MASTER_SET_PANORAMA("Master: Set Panorama", false),
    MASTER_TOGGLE_MUTE("Master: Toggle Mute", true),
    MASTER_TOGGLE_SOLO("Master: Toggle Solo", true),
    MASTER_TOGGLE_ARM("Master: Toggle Arm", true),
    DEVICE_TOGGLE_WINDOW("Device: Toggle Window", true),
    DEVICE_BYPASS("Device: Bypass", true),
    DEVICE_EXPAND("Device: Expand", true),
    DEVICE_SELECT_PREVIOUS("Device: Select Previous", true),
    DEVICE_SELECT_NEXT("Device: Select Next", true),
    DEVICE_SCROLL_DEVICES("Device: Scroll devices", false),
    DEVICE_SELECT_PREVIOUS_PARAMETER_BANK("Device: Select Previous Parameter Bank", true),
    DEVICE_SELECT_NEXT_PARAMETER_BANK("Device: Select Next Parameter Bank", true),
    DEVICE_SCROLL_PARAMETER_BANKS("Device: Scroll Parameter Banks", false),
    DEVICE_SET_PARAMETER_1("Device: Set Parameter 1", false),
    DEVICE_SET_PARAMETER_2("Device: Set Parameter 2", false),
    DEVICE_SET_PARAMETER_3("Device: Set Parameter 3", false),
    DEVICE_SET_PARAMETER_4("Device: Set Parameter 4", false),
    DEVICE_SET_PARAMETER_5("Device: Set Parameter 5", false),
    DEVICE_SET_PARAMETER_6("Device: Set Parameter 6", false),
    DEVICE_SET_PARAMETER_7("Device: Set Parameter 7", false),
    DEVICE_SET_PARAMETER_8("Device: Set Parameter 8", false),
    BROWSER_BROWSE_PRESETS("Browser: Browse Presets", true),
    BROWSER_INSERT_DEVICE_BEFORE_CURRENT("Browser: Insert Device before current", true),
    BROWSER_INSERT_DEVICE_AFTER_CURRENT("Browser: Insert Device after current", true),
    BROWSER_COMMIT_SELECTION("Browser: Commit Selection", true),
    BROWSER_CANCEL_SELECTION("Browser: Cancel Selection", true),
    BROWSER_SELECT_PREVIOUS_FILTER_IN_COLUMN_1("Browser: Select Previous Filter in Column 1", true),
    BROWSER_SELECT_PREVIOUS_FILTER_IN_COLUMN_2("Browser: Select Previous Filter in Column 2", true),
    BROWSER_SELECT_PREVIOUS_FILTER_IN_COLUMN_3("Browser: Select Previous Filter in Column 3", true),
    BROWSER_SELECT_PREVIOUS_FILTER_IN_COLUMN_4("Browser: Select Previous Filter in Column 4", true),
    BROWSER_SELECT_PREVIOUS_FILTER_IN_COLUMN_5("Browser: Select Previous Filter in Column 5", true),
    BROWSER_SELECT_PREVIOUS_FILTER_IN_COLUMN_6("Browser: Select Previous Filter in Column 6", true),
    BROWSER_SELECT_NEXT_FILTER_IN_COLUMN_1("Browser: Select Next Filter in Column 1", true),
    BROWSER_SELECT_NEXT_FILTER_IN_COLUMN_2("Browser: Select Next Filter in Column 2", true),
    BROWSER_SELECT_NEXT_FILTER_IN_COLUMN_3("Browser: Select Next Filter in Column 3", true),
    BROWSER_SELECT_NEXT_FILTER_IN_COLUMN_4("Browser: Select Next Filter in Column 4", true),
    BROWSER_SELECT_NEXT_FILTER_IN_COLUMN_5("Browser: Select Next Filter in Column 5", true),
    BROWSER_SELECT_NEXT_FILTER_IN_COLUMN_6("Browser: Select Next Filter in Column 6", true),
    BROWSER_SCROLL_FILTER_IN_COLUMN_1("Browser: Scroll Filter in Column 1", false),
    BROWSER_SCROLL_FILTER_IN_COLUMN_2("Browser: Scroll Filter in Column 2", false),
    BROWSER_SCROLL_FILTER_IN_COLUMN_3("Browser: Scroll Filter in Column 3", false),
    BROWSER_SCROLL_FILTER_IN_COLUMN_4("Browser: Scroll Filter in Column 4", false),
    BROWSER_SCROLL_FILTER_IN_COLUMN_5("Browser: Scroll Filter in Column 5", false),
    BROWSER_SCROLL_FILTER_IN_COLUMN_6("Browser: Scroll Filter in Column 6", false),
    BROWSER_RESET_FILTER_COLUMN_1("Browser: Reset Filter Column 1", true),
    BROWSER_RESET_FILTER_COLUMN_2("Browser: Reset Filter Column 2", true),
    BROWSER_RESET_FILTER_COLUMN_3("Browser: Reset Filter Column 3", true),
    BROWSER_RESET_FILTER_COLUMN_4("Browser: Reset Filter Column 4", true),
    BROWSER_RESET_FILTER_COLUMN_5("Browser: Reset Filter Column 5", true),
    BROWSER_RESET_FILTER_COLUMN_6("Browser: Reset Filter Column 6", true),
    BROWSER_SELECT_THE_PREVIOUS_PRESET("Browser: Select the previous preset", true),
    BROWSER_SELECT_THE_NEXT_PRESET("Browser: Select the next preset", true),
    BROWSER_SCROLL_PRESETS("Browser: Scroll presets", false),
    BROWSER_SELECT_THE_PREVIOUS_TAB("Browser: Select the previous tab", true),
    BROWSER_SELECT_THE_NEXT_TAB("Browser: Select the next tab", true),
    BROWSER_SCROLL_TABS("Browser: Scroll tabs", false),
    SCENE_1_LAUNCH_SCENE("Scene 1: Launch Scene", true),
    SCENE_2_LAUNCH_SCENE("Scene 2: Launch Scene", true),
    SCENE_3_LAUNCH_SCENE("Scene 3: Launch Scene", true),
    SCENE_4_LAUNCH_SCENE("Scene 4: Launch Scene", true),
    SCENE_5_LAUNCH_SCENE("Scene 5: Launch Scene", true),
    SCENE_6_LAUNCH_SCENE("Scene 6: Launch Scene", true),
    SCENE_7_LAUNCH_SCENE("Scene 7: Launch Scene", true),
    SCENE_8_LAUNCH_SCENE("Scene 8: Launch Scene", true),
    SCENE_SELECT_PREVIOUS_BANK("Scene: Select Previous Bank", true),
    SCENE_SELECT_NEXT_BANK("Scene: Select Next Bank", true),
    SCENE_CREATE_SCENE_FROM_PLAYING_CLIPS("Scene: Create Scene from playing Clips", true),
    CLIP_PREVIOUS("Clip: Select previous", true),
    CLIP_NEXT("Clip: Select next", true),
    CLIP_SCROLL("Clip: Scroll clips", false),
    CLIP_PLAY("Clip: Play", true),
    CLIP_STOP("Clip: Stop", true),
    CLIP_RECORD("Clip: Record", true),
    CLIP_NEW("Clip: New", true),
    MARKER_1_LAUNCH_MARKER("Marker 1: Launch Marker", true),
    MARKER_2_LAUNCH_MARKER("Marker 2: Launch Marker", true),
    MARKER_3_LAUNCH_MARKER("Marker 3: Launch Marker", true),
    MARKER_4_LAUNCH_MARKER("Marker 4: Launch Marker", true),
    MARKER_5_LAUNCH_MARKER("Marker 5: Launch Marker", true),
    MARKER_6_LAUNCH_MARKER("Marker 6: Launch Marker", true),
    MARKER_7_LAUNCH_MARKER("Marker 7: Launch Marker", true),
    MARKER_8_LAUNCH_MARKER("Marker 8: Launch Marker", true),
    MARKER_SELECT_PREVIOUS_BANK("Marker: Select Previous Bank", true),
    MARKER_SELECT_NEXT_BANK("Marker: Select Next Bank", true);

    private final String  name;
    private final boolean isTrigger;


    private FlexiCommand (final String name, final boolean isTrigger)
    {
        this.name = name;
        this.isTrigger = isTrigger;
    }


    public String getName ()
    {
        return this.name;
    }


    public boolean isTrigger ()
    {
        return this.isTrigger;
    }


    public static String [] getNames ()
    {
        final FlexiCommand [] values = FlexiCommand.values ();
        final String [] names = new String [values.length];
        for (int i = 0; i < values.length; i++)
            names[i] = values[i].getName ();
        return names;
    }


    public static FlexiCommand lookupByName (final String name)
    {
        final FlexiCommand [] values = FlexiCommand.values ();
        for (final FlexiCommand c: values)
        {
            if (c.getName ().equals (name))
                return c;
        }
        return values[0];
    }
}
